#!/usr/bin/env bash
# build_kernel_tcc.sh -- SELFHOST_PLAN.md SH5c: build the x86_64 kernel with
# the self-host toolchain (host tcc + mini-asm + aulink), no clang/lld/nasm
# in the tool path.
#
#   tcc   = build/selfhost/host-tcc-src/tcc   (make selfhost-deps selfhost-host-tcc)
#   asm   = tools/mini-asm/mini-asm.c         (SH4d: elf64 parity with nasm)
#   link  = tools/aulink/aulink.c             (SH3/SH5b: kernel.ld layout parity)
#   rt    = build/selfhost/libtcc1.a          (make selfhost-tcc; atomics/alloca/
#           __va_arg/__builtin_* helpers tcc's codegen calls)
#
# The object list is derived from the Makefile's own link line (make -B -n
# kernel), so membership AND order cannot drift from the clang build.  The
# asm offsets are generated by the HOST TCC (tcc-compiled gen_asm_offsets),
# proving the tcc lane does not depend on the host compiler for the TCB
# layout contract context.asm consumes.
#
# Usage: tools/selfhost/build_kernel_tcc.sh [--iso]
#   --iso   additionally pack build/selfhost/kernel-tcc.iso (dual-boot image
#           via the tree's mkisoimage_dual.sh) for the boot smoke case.
#
# Output artefacts (build/selfhost/kernel-tcc/):
#   kernel-tcc.elf   the self-host-built kernel
#   kernel-tcc.iso   with --iso
# Prints the SH5c flag-delta measurements on stdout.
set -u
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

BUILD_ISO=0
[ "${1:-}" = "--iso" ] && BUILD_ISO=1

HOST_TCC="$ROOT/build/selfhost/host-tcc-src/tcc"
LIBTCC1="$ROOT/build/selfhost/libtcc1.a"
OUT="$ROOT/build/selfhost/kernel-tcc"
mkdir -p "$OUT"

if [ ! -x "$HOST_TCC" ]; then
    echo "[selfhost] tcc build SKIP: host tcc absent -- run 'make selfhost-deps selfhost-host-tcc'" >&2
    exit 2
fi
if [ ! -f "$LIBTCC1" ]; then
    echo "[selfhost] tcc build SKIP: guest libtcc1.a absent -- run 'make selfhost-tcc'" >&2
    exit 2
fi
command -v cc >/dev/null 2>&1 || { echo "[selfhost] tcc build SKIP: host cc absent" >&2; exit 2; }
command -v readelf >/dev/null 2>&1 || { echo "[selfhost] tcc build SKIP: readelf absent" >&2; exit 2; }

# ---- 0) tools ----------------------------------------------------------
cc -std=c99 -O2 -o "$OUT/aulink" tools/aulink/aulink.c || exit 1
cc -std=c99 -O2 -o "$OUT/mini-asm" tools/mini-asm/mini-asm.c || exit 1

# ---- 1) asm offsets, generated by the HOST TCC -------------------------
# gen_asm_offsets needs the guest tcc's <stddef.h>; the host-tcc link step
# wants libtcc1.a on its library path, so stage a copy next to the binary.
TCCINC="$ROOT/build/selfhost/host-tcc-src/include"
cp "$LIBTCC1" "$OUT/libtcc1.a"
"$HOST_TCC" -I "$TCCINC" -I . -L "$OUT" -o "$OUT/gen_asm_offsets" \
    tools/gen_asm_offsets.c -ltcc1 || exit 1
"$OUT/gen_asm_offsets" > "$OUT/asm_offsets.inc" || exit 1
# The offsets must match the host-cc generator (the clang kernel's asm uses
# that one): a mismatch means the two compilers disagree on the TCB layout.
cc -I . -o "$OUT/gen_asm_offsets_cc" tools/gen_asm_offsets.c || exit 1
"$OUT/gen_asm_offsets_cc" > "$OUT/asm_offsets-cc.inc"
if ! cmp -s "$OUT/asm_offsets.inc" "$OUT/asm_offsets-cc.inc"; then
    echo "[selfhost] tcc build FAIL: tcc- and cc-generated asm offsets differ" >&2
    diff "$OUT/asm_offsets.inc" "$OUT/asm_offsets-cc.inc" | head -10 >&2
    exit 1
fi

# ---- 2) object list: the Makefile's own link line ----------------------
OBJS=$(make -B -n kernel 2>/dev/null | grep 'ld.lld' | grep -- '-T kernel.ld' | tr ' ' '\n' | grep '\.o$' | tr '\n' ' ')
[ -n "$OBJS" ] || { echo "[selfhost] tcc build FAIL: no kernel link line from make" >&2; exit 1; }
SRCS=""; ASMS=""
for o in $OBJS; do
    rel=${o#build/}
    rel=${rel%.o}
    if [ -f "$rel.c" ];   then SRCS="$SRCS $rel.c";   fi
    if [ -f "$rel.asm" ]; then ASMS="$ASMS $rel.asm"; fi
done
[ -n "$SRCS" ] || { echo "[selfhost] tcc build FAIL: no C sources derived from the link line" >&2; exit 1; }

# ---- 3) compile the C with the host tcc --------------------------------
TCFLAGS="-c -ffreestanding -fno-pic -I $TCCINC -I . -I build -I w32/include -DARCH_X86_64"
rm -rf "$OUT/obj"; mkdir -p "$OUT/obj"
n=0; fail=0
for f in $SRCS; do
    o="$OUT/obj/$(echo "$f" | tr '/' '_').o"
    if ! "$HOST_TCC" $TCFLAGS -o "$o" "$f" 2>"$OUT/last.err"; then
        echo "[selfhost] tcc build FAIL: $f" >&2
        sed 's/^/    /' "$OUT/last.err" | head -5 >&2
        fail=1
    fi
    n=$((n + 1))
done
[ $fail -eq 0 ] || exit 1
echo "[sh5c] tcc compiled $n kernel C files"

# ---- 4) assemble the .asm with mini-asm (SH4d parity) ------------------
rm -rf "$OUT/asm"; mkdir -p "$OUT/asm"
for f in $ASMS; do
    o="$OUT/asm/$(echo "$f" | tr '/' '_').o"
    "$OUT/mini-asm" -f elf64 -I "$OUT/" "$f" -o "$o" || exit 1
done
echo "[sh5c] mini-asm assembled $(echo $ASMS | wc -w) kernel asm files"

# ---- 5) libtcc1 members the tcc objects reference ----------------------
# atomic.S + stdatomic.c (__atomic_* helpers), builtin.c (__builtin_ctzll),
# alloca.S, va_list.c (__va_arg -- tcc's va_arg lowering).  The other two
# archive members (libtcc1.o, dsohandle.o) resolve nothing the kernel
# references and stay out.
rm -rf "$OUT/lib1"; mkdir -p "$OUT/lib1"
( cd "$OUT/lib1" && ar x "$LIBTCC1" atomic.o stdatomic.o builtin.o alloca.o va_list.o ) || exit 1

# ---- 6) link with aulink (object order = the clang link order) ---------
ASM_OBJS=""
for f in $ASMS; do ASM_OBJS="$ASM_OBJS $OUT/asm/$(echo "$f" | tr '/' '_').o"; done
"$OUT/aulink" -T kernel.ld -o "$ROOT/build/selfhost/kernel-tcc.elf" \
    $OUT/obj/*.o $OUT/lib1/*.o $ASM_OBJS 2>"$OUT/aulink.err" || {
    echo "[selfhost] tcc build FAIL: aulink link" >&2
    sed 's/^/    /' "$OUT/aulink.err" | head -10 >&2
    exit 1
}
echo "[sh5c] aulink linked build/selfhost/kernel-tcc.elf"

# ---- 7) flag-delta measurements ----------------------------------------
sz() { readelf -SW "$1" 2>/dev/null | awk -v s="$2" '$3==s {print $7}'; }
echo "[sh5c] tcc kernel:    .text=$(sz "$ROOT/build/selfhost/kernel-tcc.elf" .text) .rodata=$(sz "$ROOT/build/selfhost/kernel-tcc.elf" .rodata) .data=$(sz "$ROOT/build/selfhost/kernel-tcc.elf" .data) .bss=$(sz "$ROOT/build/selfhost/kernel-tcc.elf" .bss) size=$(stat -c%s "$ROOT/build/selfhost/kernel-tcc.elf")"
if [ -f "$ROOT/build/kernel.elf" ]; then
    echo "[sh5c] clang kernel: .text=$(sz "$ROOT/build/kernel.elf" .text) .rodata=$(sz "$ROOT/build/kernel.elf" .rodata) .data=$(sz "$ROOT/build/kernel.elf" .data) .bss=$(sz "$ROOT/build/kernel.elf" .bss) size=$(stat -c%s "$ROOT/build/kernel.elf")"
fi

# ---- 8) optional ISO for the boot smoke --------------------------------
if [ $BUILD_ISO -eq 1 ]; then
    EFI="$ROOT/build/boot/BOOTX64.EFI"
    [ -f "$EFI" ] || { echo "[selfhost] tcc build FAIL: $EFI absent (run 'make efi')" >&2; exit 1; }
    bash tools/mkisoimage_dual.sh "$ROOT/build/selfhost/kernel-tcc.elf" "$EFI" \
        "$ROOT/build/selfhost/kernel-tcc.iso" >/dev/null || exit 1
    echo "[sh5c] packed build/selfhost/kernel-tcc.iso"
fi
exit 0
