#!/usr/bin/env bash
# gen_kernel_build.sh -- SELFHOST_PLAN.md SH8: emit the in-guest kernel build
# script that the closure driver runs twice.
#
# This is a HOST generator (bash).  It turns the tree's authoritative source
# list into a DATA script -- /src/selfhost/kernel_build.sh in the guest.  It
# never compiles anything; the C/asm compile and link are done in-guest by the
# self-built tcc/mini-asm/aulink.  It exists only because the guest shell has
# no command substitution, no glob, no `set --`, no long variable values
# (SH_VAR_VAL_MAX=128) and a 32-argument / 512-char line limit, so it cannot
# enumerate the kernel sources itself.  The SH5d gate enumerates them host-side
# the same way (see test_selfhost_kernel_guest.sh).
#
# Usage:  tools/selfhost/gen_kernel_build.sh > /src/selfhost/kernel_build.sh
#
# The emitted script is a FLAT sequence of `run <self-built-tool> ...` lines --
# one exec per line, no bashisms -- so it runs under AuraLite's init.c shell.
# `$TCC` is a global variable the closure driver sets before `sh` runs it
# (variables live in the same process table), so the same script serves both
# loops with the stage-appropriate compiler.
set -u
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT" || exit 1

# The C / asm source set, exactly as SH5d drives it: all x86_64 kernel +
# driver C sources, the PE host-tool source, and every kernel .asm.
mapfile -t C_SRCS < <(
    { find kernel drivers -name '*.c' \
        -not -path 'kernel/arch/i386/*' \
        -not -path 'kernel/arch/riscv64/*' \
        -not -path 'kernel/arch/aarch64/*' \
        -not -path 'kernel/dt/*' \
        -not -path 'kernel/drivers/*';
      printf '%s\n' w32/src/w32_pe.c; } | LC_ALL=C sort
)
mapfile -t ASM_SRCS < <(
    find kernel drivers -name '*.asm' \
        -not -path 'kernel/arch/i386/*' \
        -not -path 'kernel/arch/riscv64/*' \
        -not -path 'kernel/arch/aarch64/*' | LC_ALL=C sort
)
C_COUNT=${#C_SRCS[@]}
ASM_COUNT=${#ASM_SRCS[@]}
if [ "$C_COUNT" -ne 126 ] || [ "$ASM_COUNT" -ne 9 ]; then
    echo "[selfhost] SH8 kernel source set drifted: $C_COUNT C, $ASM_COUNT asm (expected 126 / 9)" >&2
    exit 2
fi

emit() { printf '%s\n' "$*"; }

emit "# Auto-generated by tools/selfhost/gen_kernel_build.sh -- SH8 in-guest"
emit "# kernel build.  Run inside the guest as:"
emit "#     set TCC=/tmp/sh8/tools/tcc1"
emit "#     sh /src/selfhost/kernel_build.sh"
emit "# 126 C + 9 asm sources compiled by the self-built toolchain, linked to"
emit "# /fat/KERNEL.ELF.  Do not edit -- regenerate from the"
emit "# source list.  Flat lines only (no bashisms) for init.c's shell."
emit "# The /tmp/sh8 worktree (lib/build/cobj/aobj) is created by the closure"
emit "# driver before this per-loop script runs; re-mkdir here would fail on the"
emit "# second loop (no -p, no tolerant mkdir)."
emit ""

# ---- generated inputs the kernel C and handwritten asm consume ----------
# The four generators are built on /fat by the closure driver (its toolchain
# phase), so reference them there; the compiler is the stage compiler.
emit "# ---- generated inputs the kernel C and handwritten asm consume ----"
emit "run /tmp/sh8/tools/gen_asm_offsets /tmp/sh8/build/asm_offsets.inc"
emit "run /tmp/sh8/tools/mini-asm -f bin -I/src -o /tmp/sh8/build/ap_trampoline.bin /src/boot/smp/ap_trampoline.asm"
emit "run /tmp/sh8/tools/gen_ap_trampoline_inc /tmp/sh8/build/ap_trampoline.bin /tmp/sh8/build/ap_trampoline.inc"
emit "run /tmp/sh8/tools/gen_user_binary /src/selfhost/init.elf /tmp/sh8/build/init_bin.h init_bin"
emit ""

# ---- the 126 C sources, one `run $TCC -c` each ------------------------------
for rel in "${C_SRCS[@]}"; do
    src="/src/${rel#./}"
    obj="${rel%.c}"
    obj="${obj//\//_}"
    emit "run \$TCC -c -ffreestanding -fno-pic -DARCH_X86_64 -I/src -I/tmp/sh8 -I/tmp/sh8/build -I/src/w32/include -o /tmp/sh8/cobj/$obj.o $src"
done
emit ""

# ---- the 9 asm sources, one `run mini-asm -f elf64` each --------------------
for rel in "${ASM_SRCS[@]}"; do
    src="/src/${rel#./}"
    obj="${rel%.asm}"
    obj="${obj//\//_}"
    emit "run /tmp/sh8/tools/mini-asm -f elf64 -I/tmp/sh8/build -I/src -o /tmp/sh8/aobj/$obj.o $src"
done
emit ""

# ---- link with the self-built aulink (directory = sorted lexical object set)
emit "# ---- link with the self-built aulink (directory = sorted lexical set) ----"
emit "run /tmp/sh8/tools/aulink -T /src/kernel.ld -o /fat/KERNEL.ELF /tmp/sh8/cobj /apps/tcc/libtcc1.a /tmp/sh8/aobj"
emit "echo [selfhost] sh8: kernel assembled in-guest"

echo "[selfhost] gen_kernel_build: emitted $C_COUNT C + $ASM_COUNT asm compile lines" >&2
