/* w32_bind.c — import binding.  WIN32_PLAN.md phase W32-4 (decision D2). */

#include "w32/w32_bind.h"
#include "w32/w32_module.h"
#include "w32/w32_pe.h"
#include "w32/kernel32.h"
#include "w32/user32.h"
#include "w32/oleaut32.h"
#include "w32/w32_gen.h"

#ifndef AURALITE_W32_HOST_TEST
#include <stdio.h>
#include <string.h>
#else
#include <stdio.h>
#include <string.h>
#endif

/* Case-insensitive compare for DLL names: an import table may say
 * "KERNEL32.dll", "kernel32.DLL" or any mixture, and Windows treats them as
 * the same module. */
static int ieq(const char *a, const char *b) {
    while (*a && *b) {
        char ca = *a, cb = *b;
        if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
        if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
        if (ca != cb) return 0;
        a++; b++;
    }
    return *a == 0 && *b == 0;
}

#define K32 "KERNEL32.dll"
#define U32 "USER32.dll"
#define G32 "GDI32.dll"
#define OA32 "OLEAUT32.dll"

/* The table is written out longhand rather than generated by a macro so that
 * `grep` finds every exported name, and so a reviewer can see the whole
 * surface at once.  D7: it grows only when a gate binary needs something. */
static const w32_export_t exports[] = {
    { K32, "CloseHandle",      (void *)CloseHandle      },
    { K32, "CreateFileA",      (void *)CreateFileA      },
    { K32, "ExitProcess",      (void *)ExitProcess      },
    { K32, "GetCommandLineA",  (void *)GetCommandLineA  },
    /* W32-7: dynamic loading.  GetProcAddress can hand back a pointer to any
     * of the above, including itself. */
    { K32, "FreeLibrary",      (void *)w32_FreeLibrary     },
    { K32, "GetModuleHandleA", (void *)w32_GetModuleHandleA },
    { K32, "GetProcAddress",   (void *)w32_GetProcAddress  },
    { K32, "LoadLibraryA",     (void *)w32_LoadLibraryA    },
    { K32, "GetLastError",     (void *)GetLastError     },
    { K32, "GetProcessHeap",   (void *)GetProcessHeap   },
    { K32, "GetStdHandle",     (void *)GetStdHandle     },
    { K32, "GetTickCount64",   (void *)GetTickCount64   },
    { K32, "HeapAlloc",        (void *)HeapAlloc        },
    { K32, "HeapFree",         (void *)HeapFree         },
    { K32, "ReadFile",         (void *)ReadFile         },
    { K32, "SetLastError",     (void *)SetLastError     },
    { K32, "Sleep",            (void *)Sleep            },
    { K32, "VirtualAlloc",     (void *)VirtualAlloc     },
    { K32, "VirtualFree",      (void *)VirtualFree      },
    { K32, "WriteFile",        (void *)WriteFile        },

    /* USER32 (W32-5).  Windowing and the message loop, mapped onto the
     * existing compositor -- see w32/src/user32.c and plan decision D5. */
    { U32, "CreateWindowExA",  (void *)CreateWindowExA  },
    { U32, "DefWindowProcA",   (void *)DefWindowProcA   },
    { U32, "DestroyWindow",    (void *)DestroyWindow    },
    { U32, "DispatchMessageA", (void *)DispatchMessageA },
    { U32, "GetClientRect",    (void *)GetClientRect    },
    { U32, "GetMessageA",      (void *)GetMessageA      },
    { U32, "InvalidateRect",   (void *)InvalidateRect   },
    { U32, "MessageBoxA",      (void *)MessageBoxA      },
    { U32, "PeekMessageA",     (void *)PeekMessageA     },
    { U32, "PostQuitMessage",  (void *)PostQuitMessage  },
    { U32, "RegisterClassExA", (void *)RegisterClassExA },
    { U32, "ShowWindow",       (void *)ShowWindow       },
    { U32, "TranslateMessage", (void *)TranslateMessage },
    { U32, "UpdateWindow",     (void *)UpdateWindow     },

    /* BeginPaint/EndPaint/FillRect live in USER32 on Windows, not GDI32,
     * even though they are drawing calls.  Listed where they really are, so
     * an import table produced by a real toolchain resolves. */
    { U32, "BeginPaint",       (void *)BeginPaint       },
    { U32, "EndPaint",         (void *)EndPaint         },
    { U32, "FillRect",         (void *)FillRect         },

    /* GDI32 (W32-5). */
    { G32, "CreateSolidBrush", (void *)CreateSolidBrush },
    { G32, "DeleteObject",     (void *)DeleteObject     },
    { G32, "LineTo",           (void *)LineTo           },
    { G32, "MoveToEx",         (void *)MoveToEx         },
    { G32, "SetPixel",         (void *)SetPixel         },
    { G32, "SetTextColor",     (void *)SetTextColor     },
    { G32, "TextOutA",         (void *)TextOutA         },

    /* OLEAUT32 (W32A-1).  The eight ladder-measured BSTR/VARIANT functions
     * are REAL already -- pure libc with no OS surface, implemented in
     * w32/src/w32_oleaut32.c.  The rest of OLEAUT32 arrives with W32A-11. */
    { OA32, "SysAllocString",        (void *)SysAllocString        },
    { OA32, "SysAllocStringLen",     (void *)SysAllocStringLen     },
    { OA32, "SysAllocStringByteLen", (void *)SysAllocStringByteLen },
    { OA32, "SysFreeString",         (void *)SysFreeString         },
    { OA32, "SysStringLen",          (void *)SysStringLen          },
    { OA32, "SysStringByteLen",      (void *)SysStringByteLen      },
    { OA32, "VariantClear",          (void *)VariantClear          },
    { OA32, "VariantCopy",           (void *)VariantCopy           },
    /* KERNEL32 (W32A-2).  Every guest-importable W32ABI definition
     * from the four phase files, so the tested implementation shadows
     * the generated TODO stub.  Deliberate gaps: FreeLibrary stays with
     * W32-7's loader-aware w32_FreeLibrary above; w32_wsprintf_core is
     * internal (W32A-5's user32 forwarder calls it); and the Char/IsChar
     * family plus IsTextUnicode are NOT kernel32 exports on Windows
     * (user32 / advapi32 own them per the ledger) so they stay
     * unbound here — the W32A-2 code implements them, W32A-5 binds the
     * user32 ones, and the ledger's name-only gap math must not see a
     * kernel32 row close a user32 symbol. */
    /* kernel32_fs.c: files, paths, time. */
    { K32, "FindFirstFileW",             (void *)FindFirstFileW             },
    { K32, "FindFirstFileA",             (void *)FindFirstFileA             },
    { K32, "FindNextFileW",              (void *)FindNextFileW              },
    { K32, "FindNextFileA",              (void *)FindNextFileA              },
    { K32, "FindClose",                  (void *)FindClose                  },
    { K32, "FindFirstFileExW",           (void *)FindFirstFileExW           },
    { K32, "FindFirstStreamW",           (void *)FindFirstStreamW           },
    { K32, "FindNextStreamW",            (void *)FindNextStreamW            },
    { K32, "FindFirstChangeNotificationW",(void *)FindFirstChangeNotificationW},
    { K32, "FindNextChangeNotification", (void *)FindNextChangeNotification },
    { K32, "FindCloseChangeNotification",(void *)FindCloseChangeNotification},
    { K32, "GetFileAttributesW",         (void *)GetFileAttributesW         },
    { K32, "GetFileAttributesExW",       (void *)GetFileAttributesExW       },
    { K32, "SetFileAttributesW",         (void *)SetFileAttributesW         },
    { K32, "CopyFileW",                  (void *)CopyFileW                  },
    { K32, "CopyFileExW",                (void *)CopyFileExW                },
    { K32, "MoveFileW",                  (void *)MoveFileW                  },
    { K32, "MoveFileExW",                (void *)MoveFileExW                },
    { K32, "MoveFileWithProgressW",      (void *)MoveFileWithProgressW      },
    { K32, "ReplaceFileW",               (void *)ReplaceFileW               },
    { K32, "DeleteFileA",                (void *)DeleteFileA                },
    { K32, "DeleteFileW",                (void *)DeleteFileW                },
    { K32, "RemoveDirectoryW",           (void *)RemoveDirectoryW           },
    { K32, "CreateDirectoryW",           (void *)CreateDirectoryW           },
    { K32, "CreateHardLinkW",            (void *)CreateHardLinkW            },
    { K32, "GetCompressedFileSizeW",     (void *)GetCompressedFileSizeW     },
    { K32, "GetDiskFreeSpaceW",          (void *)GetDiskFreeSpaceW          },
    { K32, "GetDiskFreeSpaceExW",        (void *)GetDiskFreeSpaceExW        },
    { K32, "GetDriveTypeW",              (void *)GetDriveTypeW              },
    { K32, "GetLogicalDriveStringsW",    (void *)GetLogicalDriveStringsW    },
    { K32, "GetVolumeInformationW",      (void *)GetVolumeInformationW      },
    { K32, "GetFinalPathNameByHandleW",  (void *)GetFinalPathNameByHandleW  },
    { K32, "GetFullPathNameW",           (void *)GetFullPathNameW           },
    { K32, "GetLongPathNameW",           (void *)GetLongPathNameW           },
    { K32, "SetFileTime",                (void *)SetFileTime                },
    { K32, "FileTimeToLocalFileTime",    (void *)FileTimeToLocalFileTime    },
    { K32, "FileTimeToSystemTime",       (void *)FileTimeToSystemTime       },
    { K32, "FileTimeToDosDateTime",      (void *)FileTimeToDosDateTime      },
    { K32, "DosDateTimeToFileTime",      (void *)DosDateTimeToFileTime      },
    { K32, "LocalFileTimeToFileTime",    (void *)LocalFileTimeToFileTime    },
    { K32, "CompareFileTime",            (void *)CompareFileTime            },
    { K32, "SystemTimeToTzSpecificLocalTime",(void *)SystemTimeToTzSpecificLocalTime},
    { K32, "GetSystemTimeAsFileTime",    (void *)GetSystemTimeAsFileTime    },
    { K32, "GetLocalTime",               (void *)GetLocalTime               },
    { K32, "GetTimeZoneInformation",     (void *)GetTimeZoneInformation     },
    { K32, "QueryPerformanceCounter",    (void *)QueryPerformanceCounter    },
    { K32, "QueryPerformanceFrequency",  (void *)QueryPerformanceFrequency  },
    { K32, "CreateFileW",                (void *)CreateFileW                },
    { K32, "SetFilePointer",             (void *)SetFilePointer             },
    { K32, "SetFilePointerEx",           (void *)SetFilePointerEx           },
    { K32, "SetEndOfFile",               (void *)SetEndOfFile               },
    { K32, "FlushFileBuffers",           (void *)FlushFileBuffers           },
    { K32, "GetFileSize",                (void *)GetFileSize                },
    { K32, "GetFileSizeEx",              (void *)GetFileSizeEx              },
    { K32, "GetFileType",                (void *)GetFileType                },
    { K32, "GetFileInformationByHandle", (void *)GetFileInformationByHandle },
    { K32, "GetOverlappedResult",        (void *)GetOverlappedResult        },
    { K32, "SetHandleInformation",       (void *)SetHandleInformation       },
    { K32, "CreateFileMappingW",         (void *)CreateFileMappingW         },
    { K32, "CreateFileMappingA",         (void *)CreateFileMappingA         },
    { K32, "MapViewOfFile",              (void *)MapViewOfFile              },
    { K32, "UnmapViewOfFile",            (void *)UnmapViewOfFile            },
    { K32, "CreatePipe",                 (void *)CreatePipe                 },
    { K32, "CreateNamedPipeA",           (void *)CreateNamedPipeA           },
    { K32, "ConnectNamedPipe",           (void *)ConnectNamedPipe           },
    { K32, "WaitNamedPipeA",             (void *)WaitNamedPipeA             },
    { K32, "CancelIo",                   (void *)CancelIo                   },
    { K32, "DeviceIoControl",            (void *)DeviceIoControl            },
    /* kernel32_ps.c: processes, modules, environment, system info. */
    { K32, "CreateProcessW",             (void *)CreateProcessW             },
    { K32, "CreateProcessA",             (void *)CreateProcessA             },
    { K32, "GetStartupInfoA",            (void *)GetStartupInfoA            },
    { K32, "GetStartupInfoW",            (void *)GetStartupInfoW            },
    { K32, "GetExitCodeProcess",         (void *)GetExitCodeProcess         },
    { K32, "TerminateProcess",           (void *)TerminateProcess           },
    { K32, "OpenProcess",                (void *)OpenProcess                },
    { K32, "GetProcessTimes",            (void *)GetProcessTimes            },
    { K32, "GetCurrentProcess",          (void *)GetCurrentProcess          },
    { K32, "GetCurrentProcessId",        (void *)GetCurrentProcessId        },
    { K32, "GetModuleFileNameA",         (void *)GetModuleFileNameA         },
    { K32, "GetModuleFileNameW",         (void *)GetModuleFileNameW         },
    { K32, "GetModuleHandleW",           (void *)GetModuleHandleW           },
    { K32, "GetModuleHandleExW",         (void *)GetModuleHandleExW         },
    { K32, "GetCommandLineW",            (void *)GetCommandLineW            },
    { K32, "GetEnvironmentStringsW",     (void *)GetEnvironmentStringsW     },
    { K32, "FreeEnvironmentStringsW",    (void *)FreeEnvironmentStringsW    },
    { K32, "GetEnvironmentVariableA",    (void *)GetEnvironmentVariableA    },
    { K32, "SetEnvironmentVariableW",    (void *)SetEnvironmentVariableW    },
    { K32, "ExpandEnvironmentStringsW",  (void *)ExpandEnvironmentStringsW  },
    { K32, "GetCurrentDirectoryA",       (void *)GetCurrentDirectoryA       },
    { K32, "GetCurrentDirectoryW",       (void *)GetCurrentDirectoryW       },
    { K32, "SetCurrentDirectoryA",       (void *)SetCurrentDirectoryA       },
    { K32, "SetCurrentDirectoryW",       (void *)SetCurrentDirectoryW       },
    { K32, "GetTempPathA",               (void *)GetTempPathA               },
    { K32, "GetTempPathW",               (void *)GetTempPathW               },
    { K32, "GetWindowsDirectoryA",       (void *)GetWindowsDirectoryA       },
    { K32, "GetWindowsDirectoryW",       (void *)GetWindowsDirectoryW       },
    { K32, "GetSystemDirectoryA",        (void *)GetSystemDirectoryA        },
    { K32, "GetVersion",                 (void *)GetVersion                 },
    { K32, "GetVersionExW",              (void *)GetVersionExW              },
    { K32, "GetProductInfo",             (void *)GetProductInfo             },
    { K32, "GetProcessAffinityMask",     (void *)GetProcessAffinityMask     },
    { K32, "CreateToolhelp32Snapshot",   (void *)CreateToolhelp32Snapshot   },
    { K32, "Process32FirstW",            (void *)Process32FirstW            },
    { K32, "Process32NextW",             (void *)Process32NextW             },
    { K32, "IsDebuggerPresent",          (void *)IsDebuggerPresent          },
    { K32, "IsProcessorFeaturePresent",  (void *)IsProcessorFeaturePresent  },
    { K32, "GetNativeSystemInfo",        (void *)GetNativeSystemInfo        },
    { K32, "GetSystemInfo",              (void *)GetSystemInfo              },
    { K32, "Beep",                       (void *)Beep                       },
    { K32, "SleepEx",                    (void *)SleepEx                    },
    { K32, "OutputDebugStringW",         (void *)OutputDebugStringW         },
    { K32, "RegisterApplicationRestart", (void *)RegisterApplicationRestart },
    { K32, "UnregisterApplicationRestart",(void *)UnregisterApplicationRestart},
    { K32, "GetApplicationRestartSettings",(void *)GetApplicationRestartSettings},
    { K32, "MulDiv",                     (void *)MulDiv                     },
    { K32, "EncodePointer",              (void *)EncodePointer              },
    { K32, "DecodePointer",              (void *)DecodePointer              },
    { K32, "GlobalMemoryStatus",         (void *)GlobalMemoryStatus         },
    { K32, "GlobalMemoryStatusEx",       (void *)GlobalMemoryStatusEx       },
    { K32, "LoadLibraryW",               (void *)LoadLibraryW               },
    { K32, "LoadLibraryExA",             (void *)LoadLibraryExA             },
    { K32, "LoadLibraryExW",             (void *)LoadLibraryExW             },
    /* kernel32_loc.c: locale, conversion, lstr, date/time formats. */
    { K32, "GetACP",                     (void *)GetACP                     },
    { K32, "GetOEMCP",                   (void *)GetOEMCP                   },
    { K32, "GetCPInfo",                  (void *)GetCPInfo                  },
    { K32, "IsValidCodePage",            (void *)IsValidCodePage            },
    { K32, "IsDBCSLeadByteEx",           (void *)IsDBCSLeadByteEx           },
    { K32, "GetUserDefaultLCID",         (void *)GetUserDefaultLCID         },
    { K32, "GetUserDefaultLangID",       (void *)GetUserDefaultLangID       },
    { K32, "GetSystemDefaultLangID",     (void *)GetSystemDefaultLangID     },
    { K32, "IsValidLocale",              (void *)IsValidLocale              },
    { K32, "EnumSystemLocalesW",         (void *)EnumSystemLocalesW         },
    { K32, "GetStringTypeExW",           (void *)GetStringTypeExW           },
    { K32, "GetStringTypeW",             (void *)GetStringTypeW             },
    { K32, "GetStringTypeExA",           (void *)GetStringTypeExA           },
    { K32, "GetLocaleInfoW",             (void *)GetLocaleInfoW             },
    { K32, "GetLocaleInfoA",             (void *)GetLocaleInfoA             },
    { K32, "GetLocaleInfoEx",            (void *)GetLocaleInfoEx            },
    { K32, "CompareStringW",             (void *)CompareStringW             },
    { K32, "CompareStringEx",            (void *)CompareStringEx            },
    { K32, "LCMapStringW",               (void *)LCMapStringW               },
    { K32, "LCMapStringEx",              (void *)LCMapStringEx              },
    { K32, "LCMapStringA",               (void *)LCMapStringA               },
    { K32, "MultiByteToWideChar",        (void *)MultiByteToWideChar        },
    { K32, "WideCharToMultiByte",        (void *)WideCharToMultiByte        },
    { K32, "lstrcmpW",                   (void *)lstrcmpW                   },
    { K32, "lstrcmpiA",                  (void *)lstrcmpiA                  },
    { K32, "lstrcmpiW",                  (void *)lstrcmpiW                  },
    { K32, "lstrcpyW",                   (void *)lstrcpyW                   },
    { K32, "lstrcpynA",                  (void *)lstrcpynA                  },
    { K32, "lstrcpynW",                  (void *)lstrcpynW                  },
    { K32, "lstrcatW",                   (void *)lstrcatW                   },
    { K32, "lstrlenW",                   (void *)lstrlenW                   },
    { K32, "GetDateFormatW",             (void *)GetDateFormatW             },
    { K32, "GetDateFormatEx",            (void *)GetDateFormatEx            },
    { K32, "GetTimeFormatW",             (void *)GetTimeFormatW             },
    { K32, "GetTimeFormatEx",            (void *)GetTimeFormatEx            },
    /* w32_msg.c: messages. */
    { K32, "FormatMessageW",             (void *)FormatMessageW             },
    { K32, "FormatMessageA",             (void *)FormatMessageA             },
    /* kernel32.c: the W32A-2 heap group joins the older heap rows. */
    { K32, "GetLargePageMinimum",        (void *)GetLargePageMinimum        },
    { K32, "GetTickCount",               (void *)GetTickCount               },
    { K32, "GlobalAlloc",                (void *)GlobalAlloc                },
    { K32, "GlobalFree",                 (void *)GlobalFree                 },
    { K32, "GlobalLock",                 (void *)GlobalLock                 },
    { K32, "GlobalSize",                 (void *)GlobalSize                 },
    { K32, "GlobalUnlock",               (void *)GlobalUnlock               },
    { K32, "HeapReAlloc",                (void *)HeapReAlloc                },
    { K32, "HeapSize",                   (void *)HeapSize                   },
    { K32, "LocalAlloc",                 (void *)LocalAlloc                 },
    { K32, "LocalFree",                  (void *)LocalFree                  },
    { K32, "VirtualProtect",             (void *)VirtualProtect             },
    { 0, 0, 0 }
};

const w32_export_t *w32_exports(void) { return exports; }

void *w32_resolve(const char *dll, const char *name) {
    if (!dll || !name) return 0;
    for (const w32_export_t *e = exports; e->dll; e++) {
        if (!ieq(e->dll, dll)) continue;
        if (strcmp(e->name, name) == 0) return e->addr;
    }
    /* W32A-1: the generated table (TODO/FAILCLEAN stubs, data cells).  The
     * static table wins ties -- a real implementation always shadows the
     * stub it replaces, so behaviour phases cannot be masked by W32A-1. */
    for (const w32_export_t *e = w32_gen_exports(); e->dll; e++) {
        if (!ieq(e->dll, dll)) continue;
        if (strcmp(e->name, name) == 0) return e->addr;
    }
    return 0;
}

/* Write a 64-bit value into the mapped image.  The IAT is writable: the
 * loader maps .idata/.rdata per the section characteristics, and a PE that
 * marks its IAT read-only would fault here -- which is correct, and better
 * than silently mapping everything writable. */
static void poke64(uint64_t addr, uint64_t val) {
    uint8_t *p = (uint8_t *)(uintptr_t)addr;
    for (int i = 0; i < 8; i++) p[i] = (uint8_t)((val >> (i * 8)) & 0xFF);
}

int w32_bind_imports(const uint8_t *image, size_t image_size, uint64_t base,
                     const char **missing_dll, const char **missing_name) {
    /* Frame-local, NOT static: binding recurses (load_one -> map_dll ->
     * w32_bind_imports), and a shared array means the inner bind refills
     * what the outer loop is still reading -- the outer bind then
     * resolves the inner DLL's names and pokes the inner DLL's IAT RVAs
     * into its own image (W32A-1: chain_a's bind died on chain_b's
     * GetStdHandle).  256 entries x ~208 bytes x depth 8 fits any thread
     * stack several times over. */
    pe_import_t imports[256];
    /* The missings outlive the return (the caller prints them), so they
     * need stable storage of their own.  Single-flight: filled, then the
     * caller prints before any further bind -- like ordfmt below. */
    static char miss_dll[64], miss_name[128];
    pe_image_t img;
    size_t count = 0;

    if (missing_dll)  *missing_dll = 0;
    if (missing_name) *missing_name = 0;

    if (pe_parse(image, image_size, &img) != PE_OK) return -1;

    int rc = pe_imports(&img, imports, sizeof imports / sizeof imports[0], &count);
    if (rc != PE_OK) return -2;
    if (count == 0) return 0;                       /* nothing to bind */
    if (count > sizeof imports / sizeof imports[0]) return -3;

    for (size_t i = 0; i < count; i++) {
        pe_import_t *im = &imports[i];
        const char *name = im->name;
        static char ordfmt[16];

        /* Import by ordinal: the ordinal map names it (W32A-1), and the
         * name resolves like any other -- InitCommonControls answers to
         * both spellings, which is the plan's same-table alias.  Unknown
         * ordinals refuse BY NUMBER (D9), in the ledger's #<n> spelling. */
        if (im->by_ordinal) {
            const char *canon = w32_ordmap_lookup(im->dll, im->ordinal);
            if (!canon) {
                snprintf(ordfmt, sizeof ordfmt, "#%u", im->ordinal);
                snprintf(miss_dll, sizeof miss_dll, "%s", im->dll);
                if (missing_dll)  *missing_dll = miss_dll;
                if (missing_name) *missing_name = ordfmt;
                return -4;
            }
            name = canon;
        }

        /* Built-ins first (static, then generated stubs), then other user
         * DLLs, loaded recursively.  A dependency that will not load fails
         * the bind with the import named. */
        void *fn = w32_resolve(im->dll, name);
        if (!fn)
            fn = w32_load_dependency(im->dll, name, im->by_ordinal,
                                     im->ordinal);
        if (!fn) {
            snprintf(miss_dll, sizeof miss_dll, "%s", im->dll);
            snprintf(miss_name, sizeof miss_name, "%s", name);
            if (missing_dll)  *missing_dll = miss_dll;
            if (missing_name) *missing_name = miss_name;
            return -5;
        }
        poke64(base + im->iat_rva, (uint64_t)(uintptr_t)fn);
    }
    return 0;
}
