/* w32_bind.c — import binding.  WIN32_PLAN.md phase W32-4 (decision D2). */

#include "w32/w32_bind.h"
#include "w32/w32_pe.h"
#include "w32/kernel32.h"

#ifndef AURALITE_W32_HOST_TEST
#include <string.h>
#else
#include <string.h>
#endif

/* Case-insensitive compare for DLL names: an import table may say
 * "KERNEL32.dll", "kernel32.DLL" or any mixture, and Windows treats them as
 * the same module. */
static int ieq(const char *a, const char *b) {
    while (*a && *b) {
        char ca = *a, cb = *b;
        if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
        if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
        if (ca != cb) return 0;
        a++; b++;
    }
    return *a == 0 && *b == 0;
}

#define K32 "KERNEL32.dll"

/* The table is written out longhand rather than generated by a macro so that
 * `grep` finds every exported name, and so a reviewer can see the whole
 * surface at once.  D7: it grows only when a gate binary needs something. */
static const w32_export_t exports[] = {
    { K32, "CloseHandle",      (void *)CloseHandle      },
    { K32, "CreateFileA",      (void *)CreateFileA      },
    { K32, "ExitProcess",      (void *)ExitProcess      },
    { K32, "GetCommandLineA",  (void *)GetCommandLineA  },
    { K32, "GetLastError",     (void *)GetLastError     },
    { K32, "GetProcessHeap",   (void *)GetProcessHeap   },
    { K32, "GetStdHandle",     (void *)GetStdHandle     },
    { K32, "GetTickCount64",   (void *)GetTickCount64   },
    { K32, "HeapAlloc",        (void *)HeapAlloc        },
    { K32, "HeapFree",         (void *)HeapFree         },
    { K32, "ReadFile",         (void *)ReadFile         },
    { K32, "SetLastError",     (void *)SetLastError     },
    { K32, "Sleep",            (void *)Sleep            },
    { K32, "VirtualAlloc",     (void *)VirtualAlloc     },
    { K32, "VirtualFree",      (void *)VirtualFree      },
    { K32, "WriteFile",        (void *)WriteFile        },
    { 0, 0, 0 }
};

const w32_export_t *w32_exports(void) { return exports; }

void *w32_resolve(const char *dll, const char *name) {
    if (!dll || !name) return 0;
    for (const w32_export_t *e = exports; e->dll; e++) {
        if (!ieq(e->dll, dll)) continue;
        if (strcmp(e->name, name) == 0) return e->addr;
    }
    return 0;
}

/* Write a 64-bit value into the mapped image.  The IAT is writable: the
 * loader maps .idata/.rdata per the section characteristics, and a PE that
 * marks its IAT read-only would fault here -- which is correct, and better
 * than silently mapping everything writable. */
static void poke64(uint64_t addr, uint64_t val) {
    uint8_t *p = (uint8_t *)(uintptr_t)addr;
    for (int i = 0; i < 8; i++) p[i] = (uint8_t)((val >> (i * 8)) & 0xFF);
}

int w32_bind_imports(const uint8_t *image, size_t image_size, uint64_t base,
                     const char **missing_dll, const char **missing_name) {
    static pe_import_t imports[256];
    pe_image_t img;
    size_t count = 0;

    if (missing_dll)  *missing_dll = 0;
    if (missing_name) *missing_name = 0;

    if (pe_parse(image, image_size, &img) != PE_OK) return -1;

    int rc = pe_imports(&img, imports, sizeof imports / sizeof imports[0], &count);
    if (rc != PE_OK) return -2;
    if (count == 0) return 0;                       /* nothing to bind */
    if (count > sizeof imports / sizeof imports[0]) return -3;

    for (size_t i = 0; i < count; i++) {
        pe_import_t *im = &imports[i];

        /* Import by ordinal needs an ordinal->name map this personality does
         * not have.  Refusing is honest; guessing would bind the wrong
         * function and fail somewhere else entirely. */
        if (im->by_ordinal) {
            if (missing_dll)  *missing_dll = im->dll;
            if (missing_name) *missing_name = "<by ordinal>";
            return -4;
        }

        void *fn = w32_resolve(im->dll, im->name);
        if (!fn) {
            if (missing_dll)  *missing_dll = im->dll;
            if (missing_name) *missing_name = im->name;
            return -5;
        }
        poke64(base + im->iat_rva, (uint64_t)(uintptr_t)fn);
    }
    return 0;
}
