/* w32_bind.c — import binding.  WIN32_PLAN.md phase W32-4 (decision D2). */

#include "w32/w32_bind.h"
#include "w32/w32_module.h"
#include "w32/w32_pe.h"
#include "w32/kernel32.h"
#include "w32/user32.h"
#include "w32/gdi32.h"
#include "w32/comctl32.h"
#include "w32/advapi32.h"
#include "w32/w32_rsrc.h"
#include "w32/oleaut32.h"
#include "w32/w32_seh.h"
#include "w32/w32_gen.h"
#include "w32/w32_utf.h"

#ifndef AURALITE_W32_HOST_TEST
#include <stdio.h>
#include <string.h>
#else
#include <stdio.h>
#include <string.h>
#endif

/* Case-insensitive compare for DLL names: an import table may say
 * "KERNEL32.dll", "kernel32.DLL" or any mixture, and Windows treats them as
 * the same module. */
static int ieq(const char *a, const char *b) {
    while (*a && *b) {
        char ca = *a, cb = *b;
        if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
        if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
        if (ca != cb) return 0;
        a++; b++;
    }
    return *a == 0 && *b == 0;
}

#define K32 "KERNEL32.dll"
#define U32 "USER32.dll"
#define MCRT "msvcrt.dll"
#define G32 "GDI32.dll"
#define OA32 "OLEAUT32.dll"
#define C32 "COMCTL32.dll"
#define A32 "ADVAPI32.dll"

/* The table is written out longhand rather than generated by a macro so that
 * `grep` finds every exported name, and so a reviewer can see the whole
 * surface at once.  D7: it grows only when a gate binary needs something. */
static const w32_export_t exports[] = {
    { K32, "CloseHandle",      (void *)CloseHandle      },
    { K32, "CreateFileA",      (void *)CreateFileA      },
    { K32, "ExitProcess",      (void *)ExitProcess      },
    { K32, "GetCommandLineA",  (void *)GetCommandLineA  },
    /* W32-7: dynamic loading.  GetProcAddress can hand back a pointer to any
     * of the above, including itself. */
    { K32, "FreeLibrary",      (void *)w32_FreeLibrary     },
    { K32, "GetModuleHandleA", (void *)w32_GetModuleHandleA },
    { K32, "GetProcAddress",   (void *)w32_GetProcAddress  },
    { K32, "LoadLibraryA",     (void *)w32_LoadLibraryA    },
    { K32, "GetLastError",     (void *)GetLastError     },
    { K32, "GetProcessHeap",   (void *)GetProcessHeap   },
    { K32, "GetStdHandle",     (void *)GetStdHandle     },
    { K32, "GetTickCount64",   (void *)GetTickCount64   },
    { K32, "HeapAlloc",        (void *)HeapAlloc        },
    { K32, "HeapFree",         (void *)HeapFree         },
    { K32, "ReadFile",         (void *)ReadFile         },
    { K32, "SetLastError",     (void *)SetLastError     },
    { K32, "Sleep",            (void *)Sleep            },
    { K32, "VirtualAlloc",     (void *)VirtualAlloc     },
    { K32, "VirtualFree",      (void *)VirtualFree      },
    { K32, "WriteFile",        (void *)WriteFile        },

    /* USER32 (W32-5).  Windowing and the message loop, mapped onto the
     * existing compositor -- see w32/src/user32.c and plan decision D5. */
    { U32, "CreateWindowExA",  (void *)CreateWindowExA  },
    { U32, "DefWindowProcA",   (void *)DefWindowProcA   },
    { U32, "DestroyWindow",    (void *)DestroyWindow    },
    { U32, "DispatchMessageA", (void *)DispatchMessageA },
    { U32, "GetClientRect",    (void *)GetClientRect    },
    { U32, "GetMessageA",      (void *)GetMessageA      },
    { U32, "InvalidateRect",   (void *)InvalidateRect   },
    { U32, "MessageBoxA",      (void *)MessageBoxA      },
    { U32, "PeekMessageA",     (void *)PeekMessageA     },
    { U32, "PostQuitMessage",  (void *)PostQuitMessage  },
    { U32, "RegisterClassExA", (void *)RegisterClassExA },
    { U32, "ShowWindow",       (void *)ShowWindow       },
    { U32, "TranslateMessage", (void *)TranslateMessage },
    { U32, "UpdateWindow",     (void *)UpdateWindow     },

    /* BeginPaint/EndPaint/FillRect live in USER32 on Windows, not GDI32,
     * even though they are drawing calls.  Listed where they really are, so
     * an import table produced by a real toolchain resolves. */
    { U32, "BeginPaint",       (void *)BeginPaint       },
    { U32, "EndPaint",         (void *)EndPaint         },
    { U32, "FillRect",         (void *)FillRect         },

    /* W32A-5: the W-first window core.  D6 -- the W name is the real entry
     * point and the A name forwards; both are bound because import
     * tables name both. */
    { U32, "RegisterClassW",            (void *)RegisterClassW},
    { U32, "RegisterClassExW",          (void *)RegisterClassExW},
    { U32, "RegisterClassA",            (void *)RegisterClassA},
    { U32, "UnregisterClassW",          (void *)UnregisterClassW},
    { U32, "GetClassInfoW",             (void *)GetClassInfoW},
    { U32, "GetClassNameW",             (void *)GetClassNameW},
    { U32, "GetClassNameA",             (void *)GetClassNameA},
    { U32, "CreateWindowExW",           (void *)CreateWindowExW},
    { U32, "IsWindow",                  (void *)IsWindow},
    { U32, "GetDesktopWindow",          (void *)GetDesktopWindow},
    { U32, "GetShellWindow",            (void *)GetShellWindow},
    { U32, "GetWindowThreadProcessId",  (void *)GetWindowThreadProcessId},

    /* W32A-5: the message core.  Cross-thread sends block on a W32A-3 event
     * (see user32_win.c); WM_COMMAND/WM_NOTIFY routing is the same
     * SendMessage path a control will use in W32A-8. */
    { U32, "SendMessageW",              (void *)SendMessageW},
    { U32, "SendMessageA",              (void *)SendMessageA},
    { U32, "PostMessageW",              (void *)PostMessageW},
    { U32, "PostMessageA",              (void *)PostMessageA},
    { U32, "GetMessageW",               (void *)GetMessageW},
    { U32, "PeekMessageW",              (void *)PeekMessageW},
    { U32, "DispatchMessageW",          (void *)DispatchMessageW},
    { U32, "DefWindowProcW",            (void *)DefWindowProcW},
    { U32, "CallWindowProcW",           (void *)CallWindowProcW},
    { U32, "RegisterWindowMessageW",    (void *)RegisterWindowMessageW},
    { U32, "RegisterWindowMessageA",    (void *)RegisterWindowMessageA},
    { U32, "GetMessageTime",            (void *)GetMessageTime},
    { U32, "GetMessagePos",             (void *)GetMessagePos},
    { U32, "GetQueueStatus",            (void *)GetQueueStatus},
    { U32, "InSendMessage",             (void *)InSendMessage},
    { U32, "ReplyMessage",              (void *)ReplyMessage},
    { U32, "SendDlgItemMessageW",       (void *)SendDlgItemMessageW},
    { U32, "SendDlgItemMessageA",       (void *)SendDlgItemMessageA},
    { U32, "MsgWaitForMultipleObjects", (void *)MsgWaitForMultipleObjects},

    /* W32A-5: subclassing, window words, properties and text. */
    { U32, "SetWindowLongPtrW",         (void *)SetWindowLongPtrW},
    { U32, "GetWindowLongPtrW",         (void *)GetWindowLongPtrW},
    { U32, "SetWindowLongPtrA",         (void *)SetWindowLongPtrA},
    { U32, "GetWindowLongPtrA",         (void *)GetWindowLongPtrA},
    { U32, "GetWindowLongW",            (void *)GetWindowLongW},
    { U32, "SetWindowLongW",            (void *)SetWindowLongW},
    { U32, "GetDlgCtrlID",              (void *)GetDlgCtrlID},
    { U32, "SetWindowTextW",            (void *)SetWindowTextW},
    { U32, "SetWindowTextA",            (void *)SetWindowTextA},
    { U32, "GetWindowTextW",            (void *)GetWindowTextW},
    { U32, "GetWindowTextA",            (void *)GetWindowTextA},
    { U32, "GetWindowTextLengthW",      (void *)GetWindowTextLengthW},
    { U32, "GetWindowTextLengthA",      (void *)GetWindowTextLengthA},
    { U32, "SetPropW",                  (void *)SetPropW},
    { U32, "GetPropW",                  (void *)GetPropW},
    { U32, "RemovePropW",               (void *)RemovePropW},

    /* W32A-5: geometry, placement, visibility and Z-order.  The compositor
     * owns Z; SetWindowPos asks it rather than keeping a second stack. */
    { U32, "GetWindowRect",             (void *)GetWindowRect},
    { U32, "GetWindowPlacement",        (void *)GetWindowPlacement},
    { U32, "SetWindowPlacement",        (void *)SetWindowPlacement},
    { U32, "IsWindowVisible",           (void *)IsWindowVisible},
    { U32, "IsIconic",                  (void *)IsIconic},
    { U32, "IsZoomed",                  (void *)IsZoomed},
    { U32, "BringWindowToTop",          (void *)BringWindowToTop},
    { U32, "SetWindowPos",              (void *)SetWindowPos},
    { U32, "MoveWindow",                (void *)MoveWindow},
    { U32, "AdjustWindowRectEx",        (void *)AdjustWindowRectEx},
    { U32, "ClientToScreen",            (void *)ClientToScreen},
    { U32, "ScreenToClient",            (void *)ScreenToClient},
    { U32, "MapWindowPoints",           (void *)MapWindowPoints},
    { U32, "WindowFromPoint",           (void *)WindowFromPoint},
    { U32, "ChildWindowFromPointEx",    (void *)ChildWindowFromPointEx},
    { U32, "GetAncestor",               (void *)GetAncestor},
    { U32, "GetParent",                 (void *)GetParent},
    { U32, "SetParent",                 (void *)SetParent},
    { U32, "GetWindow",                 (void *)GetWindow},
    { U32, "IsChild",                   (void *)IsChild},
    { U32, "EnumChildWindows",          (void *)EnumChildWindows},
    { U32, "EnumThreadWindows",         (void *)EnumThreadWindows},
    { U32, "FindWindowW",               (void *)FindWindowW},
    { U32, "FindWindowA",               (void *)FindWindowA},
    { U32, "FindWindowExW",             (void *)FindWindowExW},

    /* W32A-5: focus and capture.  One focus in this compositor, so
     * GetForegroundWindow/GetActiveWindow answer with it (documented). */
    { U32, "GetFocus",                  (void *)GetFocus},
    { U32, "SetFocus",                  (void *)SetFocus},
    { U32, "GetActiveWindow",           (void *)GetActiveWindow},
    { U32, "SetActiveWindow",           (void *)SetActiveWindow},
    { U32, "GetForegroundWindow",       (void *)GetForegroundWindow},
    { U32, "SetForegroundWindow",       (void *)SetForegroundWindow},
    { U32, "GetLastActivePopup",        (void *)GetLastActivePopup},
    { U32, "FlashWindow",               (void *)FlashWindow},
    { U32, "FlashWindowEx",             (void *)FlashWindowEx},
    { U32, "GetCapture",                (void *)GetCapture},
    { U32, "SetCapture",                (void *)SetCapture},
    { U32, "ReleaseCapture",            (void *)ReleaseCapture},
    { U32, "SetLayeredWindowAttributes", (void *)SetLayeredWindowAttributes},
    { U32, "EnableWindow",              (void *)EnableWindow},
    { U32, "IsWindowEnabled",           (void *)IsWindowEnabled},

    /* W32A-5: paint, scroll and the DCs W32A-7 will grow. */
    { U32, "ValidateRect",              (void *)ValidateRect},
    { U32, "GetUpdateRgn",              (void *)GetUpdateRgn},
    { U32, "RedrawWindow",              (void *)RedrawWindow},
    { U32, "LockWindowUpdate",          (void *)LockWindowUpdate},
    { U32, "GetScrollInfo",             (void *)GetScrollInfo},
    { U32, "SetScrollInfo",             (void *)SetScrollInfo},
    { U32, "GetScrollPos",              (void *)GetScrollPos},
    { U32, "SetScrollPos",              (void *)SetScrollPos},
    { U32, "GetScrollRange",            (void *)GetScrollRange},
    { U32, "SetScrollRange",            (void *)SetScrollRange},
    { U32, "ShowScrollBar",             (void *)ShowScrollBar},
    { U32, "ScrollWindow",              (void *)ScrollWindow},
    { U32, "GetDC",                     (void *)GetDC},
    { U32, "GetDCEx",                   (void *)GetDCEx},
    { U32, "GetWindowDC",               (void *)GetWindowDC},
    { U32, "ReleaseDC",                 (void *)ReleaseDC},

    /* W32A-5: pure rectangle helpers -- host-testable, no compositor needed. */
    { U32, "EqualRect",                 (void *)EqualRect},
    { U32, "InflateRect",               (void *)InflateRect},
    { U32, "IntersectRect",             (void *)IntersectRect},
    { U32, "OffsetRect",                (void *)OffsetRect},
    { U32, "PtInRect",                  (void *)PtInRect},
    { U32, "SetRectEmpty",              (void *)SetRectEmpty},
    { U32, "IsRectEmpty",               (void *)IsRectEmpty},

    /* W32A-5: metrics, colours and parameters, taken from the compositor
     * theme (change the theme and these change -- the gate asserts it). */
    { U32, "GetSystemMetrics",          (void *)GetSystemMetrics},
    { U32, "GetSysColor",               (void *)GetSysColor},
    { U32, "GetSysColorBrush",          (void *)GetSysColorBrush},
    { U32, "SystemParametersInfoW",     (void *)SystemParametersInfoW},
    { U32, "SystemParametersInfoA",     (void *)SystemParametersInfoA},
    { U32, "GetDoubleClickTime",        (void *)GetDoubleClickTime},
    { U32, "GetCaretBlinkTime",         (void *)GetCaretBlinkTime},
    { U32, "GetKeyboardType",           (void *)GetKeyboardType},

    /* W32A-5: one monitor, and it says one rather than pretending. */
    { U32, "EnumDisplayMonitors",       (void *)EnumDisplayMonitors},
    { U32, "GetMonitorInfoW",           (void *)GetMonitorInfoW},
    { U32, "GetMonitorInfoA",           (void *)GetMonitorInfoA},
    { U32, "MonitorFromWindow",         (void *)MonitorFromWindow},
    { U32, "MonitorFromRect",           (void *)MonitorFromRect},
    { U32, "MonitorFromPoint",          (void *)MonitorFromPoint},

    /* W32A-5: input state, fed by delivered messages (see GetKeyState). */
    { U32, "GetKeyState",               (void *)GetKeyState},
    { U32, "GetKeyboardState",          (void *)GetKeyboardState},
    { U32, "SetKeyboardState",          (void *)SetKeyboardState},
    { U32, "GetKeyboardLayout",         (void *)GetKeyboardLayout},
    { U32, "MapVirtualKeyW",            (void *)MapVirtualKeyW},
    { U32, "ToAscii",                   (void *)ToAscii},
    { U32, "ToAsciiEx",                 (void *)ToAsciiEx},
    { U32, "GetCursorPos",              (void *)GetCursorPos},
    { U32, "SetCursorPos",              (void *)SetCursorPos},
    { U32, "mouse_event",               (void *)mouse_event},
    { U32, "TrackMouseEvent",           (void *)TrackMouseEvent},
    { U32, "MessageBoxW",               (void *)MessageBoxW},

    /* W32A-5 binds the Char family under USER32: Windows exports them from
     * user32, W32A-2 wrote the code (kernel32_loc.c), and the ledger's
     * gap math must see a user32 row close a user32 symbol. */
    { U32, "CharUpperW",                (void *)CharUpperW},
    { U32, "CharLowerW",                (void *)CharLowerW},
    { U32, "IsCharAlphaW",              (void *)IsCharAlphaW},
    { U32, "IsCharAlphaNumericW",       (void *)IsCharAlphaNumericW},
    { U32, "IsCharUpperW",              (void *)IsCharUpperW},
    { U32, "IsCharLowerW",              (void *)IsCharLowerW},

    { U32, "FrameRect",        (void *)FrameRect        },

    /* GDI32 (W32-5): the A-5 drawing core. */
    { G32, "CreateSolidBrush", (void *)CreateSolidBrush },
    { G32, "DeleteObject",     (void *)DeleteObject     },
    { G32, "LineTo",           (void *)LineTo           },
    { G32, "MoveToEx",         (void *)MoveToEx         },
    { G32, "SetPixel",         (void *)SetPixel         },
    { G32, "SetTextColor",     (void *)SetTextColor     },
    { G32, "TextOutA",         (void *)TextOutA         },

    /* GDI32 (W32A-7): DCs, blitting, regions, fonts, palettes -- the 80
     * ladder-measured imports the ledger showed uncovered, each with a
     * real behaviour (raster engine, object table, metrics) or a named
     * refusal (printing). */
    { G32, "BitBlt",                   (void *)BitBlt },
    { G32, "CombineRgn",               (void *)CombineRgn },
    { G32, "CreateBitmap",             (void *)CreateBitmap },
    { G32, "CreateCompatibleBitmap",   (void *)CreateCompatibleBitmap },
    { G32, "CreateCompatibleDC",       (void *)CreateCompatibleDC },
    { G32, "CreateDIBSection",         (void *)CreateDIBSection },
    { G32, "CreateFontA",              (void *)CreateFontA },
    { G32, "CreateFontIndirectA",      (void *)CreateFontIndirectA },
    { G32, "CreateFontIndirectW",      (void *)CreateFontIndirectW },
    { G32, "CreateFontW",              (void *)CreateFontW },
    { G32, "CreateHatchBrush",         (void *)CreateHatchBrush },
    { G32, "CreatePalette",            (void *)CreatePalette },
    { G32, "CreatePatternBrush",       (void *)CreatePatternBrush },
    { G32, "CreatePen",                (void *)CreatePen },
    { G32, "CreateRectRgn",            (void *)CreateRectRgn },
    { G32, "CreateRectRgnIndirect",    (void *)CreateRectRgnIndirect },
    { G32, "DPtoLP",                   (void *)DPtoLP },
    { G32, "DeleteDC",                 (void *)DeleteDC },
    { G32, "Ellipse",                  (void *)Ellipse },
    { G32, "EndDoc",                   (void *)EndDoc },
    { G32, "EndPage",                  (void *)EndPage },
    { G32, "EnumFontFamiliesExW",      (void *)EnumFontFamiliesExW },
    { G32, "ExcludeClipRect",          (void *)ExcludeClipRect },
    { G32, "ExtCreatePen",             (void *)ExtCreatePen },
    { G32, "ExtTextOutA",              (void *)ExtTextOutA },
    { G32, "ExtTextOutW",              (void *)ExtTextOutW },
    { G32, "GdiAlphaBlend",            (void *)GdiAlphaBlend },
    { G32, "GetBkMode",                (void *)GetBkMode },
    { G32, "GetCharABCWidthsFloatA",   (void *)GetCharABCWidthsFloatA },
    { G32, "GetCharWidth32A",          (void *)GetCharWidth32A },
    { G32, "GetCharWidth32W",          (void *)GetCharWidth32W },
    { G32, "GetCharWidthA",            (void *)GetCharWidthA },
    { G32, "GetCharWidthW",            (void *)GetCharWidthW },
    { G32, "GetCharacterPlacementW",   (void *)GetCharacterPlacementW },
    { G32, "GetClipRgn",               (void *)GetClipRgn },
    { G32, "GetCurrentObject",         (void *)GetCurrentObject },
    { G32, "GetDIBits",                (void *)GetDIBits },
    { G32, "GetDeviceCaps",            (void *)GetDeviceCaps },
    { G32, "GetObjectA",               (void *)GetObjectA },
    { G32, "GetObjectW",               (void *)GetObjectW },
    { G32, "GetOutlineTextMetricsA",   (void *)GetOutlineTextMetricsA },
    { G32, "GetPixel",                 (void *)GetPixel },
    { G32, "GetROP2",                  (void *)GetROP2 },
    { G32, "GetStockObject",           (void *)GetStockObject },
    { G32, "GetTextExtentExPointA",    (void *)GetTextExtentExPointA },
    { G32, "GetTextExtentExPointW",    (void *)GetTextExtentExPointW },
    { G32, "GetTextExtentPoint32A",    (void *)GetTextExtentPoint32A },
    { G32, "GetTextExtentPoint32W",    (void *)GetTextExtentPoint32W },
    { G32, "GetTextExtentPointA",      (void *)GetTextExtentPointA },
    { G32, "GetTextExtentPointW",      (void *)GetTextExtentPointW },
    { G32, "GetTextMetricsA",          (void *)GetTextMetricsA },
    { G32, "GetTextMetricsW",          (void *)GetTextMetricsW },
    { G32, "IntersectClipRect",        (void *)IntersectClipRect },
    { G32, "OffsetWindowOrgEx",        (void *)OffsetWindowOrgEx },
    { G32, "PatBlt",                   (void *)PatBlt },
    { G32, "Polygon",                  (void *)Polygon },
    { G32, "Polyline",                 (void *)Polyline },
    { G32, "RealizePalette",           (void *)RealizePalette },
    { G32, "RectVisible",              (void *)RectVisible },
    { G32, "Rectangle",                (void *)Rectangle },
    { G32, "RestoreDC",                (void *)RestoreDC },
    { G32, "RoundRect",                (void *)RoundRect },
    { G32, "SaveDC",                   (void *)SaveDC },
    { G32, "SelectClipRgn",            (void *)SelectClipRgn },
    { G32, "SelectObject",             (void *)SelectObject },
    { G32, "SelectPalette",            (void *)SelectPalette },
    { G32, "SetBkColor",               (void *)SetBkColor },
    { G32, "SetBkMode",                (void *)SetBkMode },
    { G32, "SetBrushOrgEx",            (void *)SetBrushOrgEx },
    { G32, "SetDIBits",                (void *)SetDIBits },
    { G32, "SetMapMode",               (void *)SetMapMode },
    { G32, "SetPaletteEntries",        (void *)SetPaletteEntries },
    { G32, "SetROP2",                  (void *)SetROP2 },
    { G32, "SetTextAlign",             (void *)SetTextAlign },
    { G32, "SetWindowOrgEx",           (void *)SetWindowOrgEx },
    { G32, "StartDocW",                (void *)StartDocW },
    { G32, "StartPage",                (void *)StartPage },
    { G32, "TranslateCharsetInfo",     (void *)TranslateCharsetInfo },
    { G32, "UnrealizeObject",          (void *)UnrealizeObject },
    { G32, "UpdateColors",             (void *)UpdateColors },

    /* OLEAUT32 (W32A-1).  The eight ladder-measured BSTR/VARIANT functions
     * are REAL already -- pure libc with no OS surface, implemented in
     * w32/src/w32_oleaut32.c.  The rest of OLEAUT32 arrives with W32A-11. */
    { OA32, "SysAllocString",        (void *)SysAllocString        },
    { OA32, "SysAllocStringLen",     (void *)SysAllocStringLen     },
    { OA32, "SysAllocStringByteLen", (void *)SysAllocStringByteLen },
    { OA32, "SysFreeString",         (void *)SysFreeString         },
    { OA32, "SysStringLen",          (void *)SysStringLen          },
    { OA32, "SysStringByteLen",      (void *)SysStringByteLen      },
    { OA32, "VariantClear",          (void *)VariantClear          },
    { OA32, "VariantCopy",           (void *)VariantCopy           },
    /* KERNEL32 (W32A-2).  Every guest-importable W32ABI definition
     * from the four phase files, so the tested implementation shadows
     * the generated TODO stub.  Deliberate gaps: FreeLibrary stays with
     * W32-7's loader-aware w32_FreeLibrary above; w32_wsprintf_core is
     * internal (W32A-5's user32 forwarder calls it); and the Char/IsChar
     * family plus IsTextUnicode are NOT kernel32 exports on Windows
     * (user32 / advapi32 own them per the ledger) so they stay
     * unbound here — the W32A-2 code implements them, W32A-5 binds the
     * user32 ones, and the ledger's name-only gap math must not see a
     * kernel32 row close a user32 symbol. */
    /* kernel32_fs.c: files, paths, time. */
    { K32, "FindFirstFileW",             (void *)FindFirstFileW             },
    { K32, "FindFirstFileA",             (void *)FindFirstFileA             },
    { K32, "FindNextFileW",              (void *)FindNextFileW              },
    { K32, "FindNextFileA",              (void *)FindNextFileA              },
    { K32, "FindClose",                  (void *)FindClose                  },
    { K32, "FindFirstFileExW",           (void *)FindFirstFileExW           },
    { K32, "FindFirstStreamW",           (void *)FindFirstStreamW           },
    { K32, "FindNextStreamW",            (void *)FindNextStreamW            },
    { K32, "FindFirstChangeNotificationW",(void *)FindFirstChangeNotificationW},
    { K32, "FindNextChangeNotification", (void *)FindNextChangeNotification },
    { K32, "FindCloseChangeNotification",(void *)FindCloseChangeNotification},
    { K32, "GetFileAttributesW",         (void *)GetFileAttributesW         },
    { K32, "GetFileAttributesExW",       (void *)GetFileAttributesExW       },
    { K32, "SetFileAttributesW",         (void *)SetFileAttributesW         },
    { K32, "CopyFileW",                  (void *)CopyFileW                  },
    { K32, "CopyFileExW",                (void *)CopyFileExW                },
    { K32, "MoveFileW",                  (void *)MoveFileW                  },
    { K32, "MoveFileExW",                (void *)MoveFileExW                },
    { K32, "MoveFileWithProgressW",      (void *)MoveFileWithProgressW      },
    { K32, "ReplaceFileW",               (void *)ReplaceFileW               },
    { K32, "DeleteFileA",                (void *)DeleteFileA                },
    { K32, "DeleteFileW",                (void *)DeleteFileW                },
    { K32, "RemoveDirectoryW",           (void *)RemoveDirectoryW           },
    { K32, "CreateDirectoryW",           (void *)CreateDirectoryW           },
    { K32, "CreateHardLinkW",            (void *)CreateHardLinkW            },
    { K32, "GetCompressedFileSizeW",     (void *)GetCompressedFileSizeW     },
    { K32, "GetDiskFreeSpaceW",          (void *)GetDiskFreeSpaceW          },
    { K32, "GetDiskFreeSpaceExW",        (void *)GetDiskFreeSpaceExW        },
    { K32, "GetDriveTypeW",              (void *)GetDriveTypeW              },
    { K32, "GetLogicalDriveStringsW",    (void *)GetLogicalDriveStringsW    },
    { K32, "GetVolumeInformationW",      (void *)GetVolumeInformationW      },
    { K32, "GetFinalPathNameByHandleW",  (void *)GetFinalPathNameByHandleW  },
    { K32, "GetFullPathNameW",           (void *)GetFullPathNameW           },
    { K32, "GetLongPathNameW",           (void *)GetLongPathNameW           },
    { K32, "SetFileTime",                (void *)SetFileTime                },
    { K32, "FileTimeToLocalFileTime",    (void *)FileTimeToLocalFileTime    },
    { K32, "FileTimeToSystemTime",       (void *)FileTimeToSystemTime       },
    { K32, "FileTimeToDosDateTime",      (void *)FileTimeToDosDateTime      },
    { K32, "DosDateTimeToFileTime",      (void *)DosDateTimeToFileTime      },
    { K32, "LocalFileTimeToFileTime",    (void *)LocalFileTimeToFileTime    },
    { K32, "CompareFileTime",            (void *)CompareFileTime            },
    { K32, "SystemTimeToTzSpecificLocalTime",(void *)SystemTimeToTzSpecificLocalTime},
    { K32, "GetSystemTimeAsFileTime",    (void *)GetSystemTimeAsFileTime    },
    { K32, "GetLocalTime",               (void *)GetLocalTime               },
    { K32, "GetTimeZoneInformation",     (void *)GetTimeZoneInformation     },
    { K32, "QueryPerformanceCounter",    (void *)QueryPerformanceCounter    },
    { K32, "QueryPerformanceFrequency",  (void *)QueryPerformanceFrequency  },
    { K32, "CreateFileW",                (void *)CreateFileW                },
    { K32, "SetFilePointer",             (void *)SetFilePointer             },
    { K32, "SetFilePointerEx",           (void *)SetFilePointerEx           },
    { K32, "SetEndOfFile",               (void *)SetEndOfFile               },
    { K32, "FlushFileBuffers",           (void *)FlushFileBuffers           },
    { K32, "GetFileSize",                (void *)GetFileSize                },
    { K32, "GetFileSizeEx",              (void *)GetFileSizeEx              },
    { K32, "GetFileType",                (void *)GetFileType                },
    { K32, "GetFileInformationByHandle", (void *)GetFileInformationByHandle },
    { K32, "GetOverlappedResult",        (void *)GetOverlappedResult        },
    { K32, "SetHandleInformation",       (void *)SetHandleInformation       },
    { K32, "CreateFileMappingW",         (void *)CreateFileMappingW         },
    { K32, "CreateFileMappingA",         (void *)CreateFileMappingA         },
    { K32, "MapViewOfFile",              (void *)MapViewOfFile              },
    { K32, "UnmapViewOfFile",            (void *)UnmapViewOfFile            },
    { K32, "CreatePipe",                 (void *)CreatePipe                 },
    { K32, "CreateNamedPipeA",           (void *)CreateNamedPipeA           },
    { K32, "ConnectNamedPipe",           (void *)ConnectNamedPipe           },
    { K32, "WaitNamedPipeA",             (void *)WaitNamedPipeA             },
    { K32, "CancelIo",                   (void *)CancelIo                   },
    { K32, "DeviceIoControl",            (void *)DeviceIoControl            },
    /* kernel32_ps.c: processes, modules, environment, system info. */
    { K32, "CreateProcessW",             (void *)CreateProcessW             },
    { K32, "CreateProcessA",             (void *)CreateProcessA             },
    { K32, "GetStartupInfoA",            (void *)GetStartupInfoA            },
    { K32, "GetStartupInfoW",            (void *)GetStartupInfoW            },
    { K32, "GetExitCodeProcess",         (void *)GetExitCodeProcess         },
    { K32, "TerminateProcess",           (void *)TerminateProcess           },
    { K32, "OpenProcess",                (void *)OpenProcess                },
    { K32, "GetProcessTimes",            (void *)GetProcessTimes            },
    { K32, "GetCurrentProcess",          (void *)GetCurrentProcess          },
    { K32, "GetCurrentProcessId",        (void *)GetCurrentProcessId        },
    { K32, "GetModuleFileNameA",         (void *)GetModuleFileNameA         },
    { K32, "GetModuleFileNameW",         (void *)GetModuleFileNameW         },
    { K32, "GetModuleHandleW",           (void *)GetModuleHandleW           },
    { K32, "GetModuleHandleExW",         (void *)GetModuleHandleExW         },
    { K32, "GetCommandLineW",            (void *)GetCommandLineW            },
    { K32, "GetEnvironmentStringsW",     (void *)GetEnvironmentStringsW     },
    { K32, "FreeEnvironmentStringsW",    (void *)FreeEnvironmentStringsW    },
    { K32, "GetEnvironmentVariableA",    (void *)GetEnvironmentVariableA    },
    { K32, "SetEnvironmentVariableW",    (void *)SetEnvironmentVariableW    },
    { K32, "ExpandEnvironmentStringsW",  (void *)ExpandEnvironmentStringsW  },
    { K32, "GetCurrentDirectoryA",       (void *)GetCurrentDirectoryA       },
    { K32, "GetCurrentDirectoryW",       (void *)GetCurrentDirectoryW       },
    { K32, "SetCurrentDirectoryA",       (void *)SetCurrentDirectoryA       },
    { K32, "SetCurrentDirectoryW",       (void *)SetCurrentDirectoryW       },
    { K32, "GetTempPathA",               (void *)GetTempPathA               },
    { K32, "GetTempPathW",               (void *)GetTempPathW               },
    { K32, "GetWindowsDirectoryA",       (void *)GetWindowsDirectoryA       },
    { K32, "GetWindowsDirectoryW",       (void *)GetWindowsDirectoryW       },
    { K32, "GetSystemDirectoryA",        (void *)GetSystemDirectoryA        },
    { K32, "GetVersion",                 (void *)GetVersion                 },
    { K32, "GetVersionExW",              (void *)GetVersionExW              },
    { K32, "GetProductInfo",             (void *)GetProductInfo             },
    { K32, "GetProcessAffinityMask",     (void *)GetProcessAffinityMask     },
    { K32, "CreateToolhelp32Snapshot",   (void *)CreateToolhelp32Snapshot   },
    { K32, "Process32FirstW",            (void *)Process32FirstW            },
    { K32, "Process32NextW",             (void *)Process32NextW             },
    { K32, "IsDebuggerPresent",          (void *)IsDebuggerPresent          },
    { K32, "IsProcessorFeaturePresent",  (void *)IsProcessorFeaturePresent  },
    { K32, "GetNativeSystemInfo",        (void *)GetNativeSystemInfo        },
    { K32, "GetSystemInfo",              (void *)GetSystemInfo              },
    { K32, "Beep",                       (void *)Beep                       },
    { K32, "SleepEx",                    (void *)SleepEx                    },
    { K32, "OutputDebugStringW",         (void *)OutputDebugStringW         },
    { K32, "RegisterApplicationRestart", (void *)RegisterApplicationRestart },
    { K32, "UnregisterApplicationRestart",(void *)UnregisterApplicationRestart},
    { K32, "GetApplicationRestartSettings",(void *)GetApplicationRestartSettings},
    { K32, "MulDiv",                     (void *)MulDiv                     },
    { K32, "EncodePointer",              (void *)EncodePointer              },
    { K32, "DecodePointer",              (void *)DecodePointer              },
    { K32, "GlobalMemoryStatus",         (void *)GlobalMemoryStatus         },
    { K32, "GlobalMemoryStatusEx",       (void *)GlobalMemoryStatusEx       },
    { K32, "LoadLibraryW",               (void *)LoadLibraryW               },
    { K32, "LoadLibraryExA",             (void *)LoadLibraryExA             },
    { K32, "LoadLibraryExW",             (void *)LoadLibraryExW             },
    /* kernel32_loc.c: locale, conversion, lstr, date/time formats. */
    { K32, "GetACP",                     (void *)GetACP                     },
    { K32, "GetOEMCP",                   (void *)GetOEMCP                   },
    { K32, "GetCPInfo",                  (void *)GetCPInfo                  },
    { K32, "IsValidCodePage",            (void *)IsValidCodePage            },
    { K32, "IsDBCSLeadByteEx",           (void *)IsDBCSLeadByteEx           },
    { K32, "GetUserDefaultLCID",         (void *)GetUserDefaultLCID         },
    { K32, "GetUserDefaultLangID",       (void *)GetUserDefaultLangID       },
    { K32, "GetSystemDefaultLangID",     (void *)GetSystemDefaultLangID     },
    { K32, "IsValidLocale",              (void *)IsValidLocale              },
    { K32, "EnumSystemLocalesW",         (void *)EnumSystemLocalesW         },
    { K32, "GetStringTypeExW",           (void *)GetStringTypeExW           },
    { K32, "GetStringTypeW",             (void *)GetStringTypeW             },
    { K32, "GetStringTypeExA",           (void *)GetStringTypeExA           },
    { K32, "GetLocaleInfoW",             (void *)GetLocaleInfoW             },
    { K32, "GetLocaleInfoA",             (void *)GetLocaleInfoA             },
    { K32, "GetLocaleInfoEx",            (void *)GetLocaleInfoEx            },
    { K32, "CompareStringW",             (void *)CompareStringW             },
    { K32, "CompareStringEx",            (void *)CompareStringEx            },
    { K32, "LCMapStringW",               (void *)LCMapStringW               },
    { K32, "LCMapStringEx",              (void *)LCMapStringEx              },
    { K32, "LCMapStringA",               (void *)LCMapStringA               },
    { K32, "MultiByteToWideChar",        (void *)MultiByteToWideChar        },
    { K32, "WideCharToMultiByte",        (void *)WideCharToMultiByte        },
    { K32, "lstrcmpW",                   (void *)lstrcmpW                   },
    { K32, "lstrcmpiA",                  (void *)lstrcmpiA                  },
    { K32, "lstrcmpiW",                  (void *)lstrcmpiW                  },
    { K32, "lstrcpyW",                   (void *)lstrcpyW                   },
    { K32, "lstrcpynA",                  (void *)lstrcpynA                  },
    { K32, "lstrcpynW",                  (void *)lstrcpynW                  },
    { K32, "lstrcatW",                   (void *)lstrcatW                   },
    { K32, "lstrlenW",                   (void *)lstrlenW                   },
    { K32, "GetDateFormatW",             (void *)GetDateFormatW             },
    { K32, "GetDateFormatEx",            (void *)GetDateFormatEx            },
    { K32, "GetTimeFormatW",             (void *)GetTimeFormatW             },
    { K32, "GetTimeFormatEx",            (void *)GetTimeFormatEx            },
    /* w32_msg.c: messages. */
    { K32, "FormatMessageW",             (void *)FormatMessageW             },
    { K32, "FormatMessageA",             (void *)FormatMessageA             },
    /* kernel32.c: the W32A-2 heap group joins the older heap rows. */
    { K32, "GetLargePageMinimum",        (void *)GetLargePageMinimum        },
    { K32, "GetTickCount",               (void *)GetTickCount               },
    { K32, "GlobalAlloc",                (void *)GlobalAlloc                },
    { K32, "GlobalFree",                 (void *)GlobalFree                 },
    { K32, "GlobalLock",                 (void *)GlobalLock                 },
    { K32, "GlobalSize",                 (void *)GlobalSize                 },
    { K32, "GlobalUnlock",               (void *)GlobalUnlock               },
    { K32, "HeapReAlloc",                (void *)HeapReAlloc                },
    { K32, "HeapSize",                   (void *)HeapSize                   },
    { K32, "LocalAlloc",                 (void *)LocalAlloc                 },
    { K32, "LocalFree",                  (void *)LocalFree                  },
    { K32, "VirtualProtect",             (void *)VirtualProtect             },
    /* KERNEL32 (W32A-3).  The ledger-decided threading API: threads,
     * Tls/Fls, critical sections, exclusive SRW + CV, InitOnce, SList,
     * events, mutexes, semaphores, waits, APCs, threadpool. */
    { K32, "AcquireSRWLockExclusive",    (void *)AcquireSRWLockExclusive    },
    { K32, "CloseThreadpoolWork",        (void *)CloseThreadpoolWork        },
    { K32, "CreateEventA",               (void *)CreateEventA               },
    { K32, "CreateEventW",               (void *)CreateEventW               },
    { K32, "CreateMutexA",               (void *)CreateMutexA               },
    { K32, "CreateMutexW",               (void *)CreateMutexW               },
    { K32, "CreateSemaphoreW",           (void *)CreateSemaphoreW           },
    { K32, "CreateThread",               (void *)CreateThread               },
    { K32, "CreateThreadpoolWork",       (void *)CreateThreadpoolWork       },
    { K32, "DeleteCriticalSection",      (void *)DeleteCriticalSection      },
    { K32, "EnterCriticalSection",       (void *)EnterCriticalSection       },
    { K32, "TryEnterCriticalSection",    (void *)TryEnterCriticalSection    },
    { K32, "ExitThread",                 (void *)ExitThread                 },
    { K32, "FlsAlloc",                   (void *)FlsAlloc                   },
    { K32, "FlsFree",                    (void *)FlsFree                    },
    { K32, "FlsGetValue",                (void *)FlsGetValue                },
    { K32, "FlsSetValue",                (void *)FlsSetValue                },
    { K32, "FreeLibraryAndExitThread",   (void *)FreeLibraryAndExitThread   },
    { K32, "GetCurrentThread",           (void *)GetCurrentThread           },
    { K32, "GetCurrentThreadId",         (void *)GetCurrentThreadId         },
    { K32, "GetThreadId",                (void *)GetThreadId                },
    { K32, "GetExitCodeThread",          (void *)GetExitCodeThread          },
    { K32, "GetThreadTimes",             (void *)GetThreadTimes             },
    { K32, "InitializeCriticalSection",  (void *)InitializeCriticalSection  },
    { K32, "InitializeCriticalSectionAndSpinCount",
        (void *)InitializeCriticalSectionAndSpinCount },
    { K32, "InitializeCriticalSectionEx", (void *)InitializeCriticalSectionEx },
    { K32, "InitializeSListHead",        (void *)InitializeSListHead        },
    { K32, "InitOnceBeginInitialize",    (void *)InitOnceBeginInitialize    },
    { K32, "InitOnceComplete",           (void *)InitOnceComplete           },
    { K32, "InterlockedFlushSList",      (void *)InterlockedFlushSList      },
    { K32, "LeaveCriticalSection",       (void *)LeaveCriticalSection       },
    { K32, "QueueUserAPC",               (void *)QueueUserAPC               },
    { K32, "ReleaseMutex",               (void *)ReleaseMutex               },
    { K32, "ReleaseSRWLockExclusive",    (void *)ReleaseSRWLockExclusive    },
    { K32, "ReleaseSemaphore",           (void *)ReleaseSemaphore           },
    { K32, "ResetEvent",                 (void *)ResetEvent                 },
    { K32, "ResumeThread",               (void *)ResumeThread               },
    { K32, "SetEvent",                   (void *)SetEvent                   },
    { K32, "SetThreadAffinityMask",      (void *)SetThreadAffinityMask      },
    { K32, "SleepConditionVariableSRW",  (void *)SleepConditionVariableSRW  },
    { K32, "SubmitThreadpoolWork",       (void *)SubmitThreadpoolWork       },
    { K32, "TerminateThread",            (void *)TerminateThread            },
    { K32, "TlsAlloc",                   (void *)TlsAlloc                   },
    { K32, "TlsFree",                    (void *)TlsFree                    },
    { K32, "TlsGetValue",                (void *)TlsGetValue                },
    { K32, "TlsSetValue",                (void *)TlsSetValue                },
    { K32, "TryAcquireSRWLockExclusive", (void *)TryAcquireSRWLockExclusive },
    { K32, "WaitForMultipleObjects",     (void *)WaitForMultipleObjects     },
    { K32, "WaitForSingleObject",        (void *)WaitForSingleObject        },
    { K32, "WaitForSingleObjectEx",      (void *)WaitForSingleObjectEx      },
    { K32, "WakeAllConditionVariable",   (void *)WakeAllConditionVariable   },
    /* KERNEL32 (W32A-4).  The table-driven unwinder: fault dispatch
     * consults the guest .pdata live (see w32_seh.c), and the Rtl family
     * is how foreign personalities (libgcc's __gxx_personality_seh0)
     * drive the same tables. */
    { K32, "RaiseException",             (void *)RaiseException             },
    { K32, "RtlCaptureContext",          (void *)RtlCaptureContext          },
    { K32, "RtlLookupFunctionEntry",     (void *)RtlLookupFunctionEntry     },
    { K32, "RtlPcToFileHeader",          (void *)RtlPcToFileHeader          },
    { K32, "RtlUnwind",                  (void *)RtlUnwind                  },
    { K32, "RtlUnwindEx",                (void *)RtlUnwindEx                },
    { K32, "RtlVirtualUnwind",           (void *)RtlVirtualUnwind           },
    { K32, "SetUnhandledExceptionFilter", (void *)SetUnhandledExceptionFilter },
    { K32, "UnhandledExceptionFilter",   (void *)UnhandledExceptionFilter   },
    { K32, "_XcptFilter",                (void *)_XcptFilter                },
    { K32, "__C_specific_handler",       (void *)__C_specific_handler       },
    /* msvcrt (W32A-4, D7).  The static table shadows the W32A-13 TODO
     * stubs: the throw sweeps real cleanups, the two deaths are named. */
    { MCRT, "_CxxThrowException",        (void *)_CxxThrowException        },
    { MCRT, "?terminate@@YAXXZ",         (void *)w32_cxx_terminate          },
    { MCRT, "_purecall",                 (void *)_purecall                 },
    /* The CRT re-exports both handlers (every ladder binary imports them
     * from msvcrt, not kernel32): same functions, second spelling. */
    { MCRT, "_XcptFilter",               (void *)_XcptFilter               },
    { MCRT, "__C_specific_handler",      (void *)__C_specific_handler      },

    /* W32A-6: USER32 breadth II — dialogs, menus, timers, carets,
     * accelerators, clipboard, hooks, DrawText family, and the resource
     * APIs.  Functions are defined in w32/src/w32_dlg.c (dialogs/menus/
     * timers/caret/accel/clipboard/hooks/draw) and w32/src/w32_rsrc.c
     * (FindResource/LoadString/LoadIcon/etc.). */
    /* Resources (mostly USER32, plus a few KERNEL32 spellings kept here
     * because every binary imports them from whichever DLL it guessed). */
    { K32, "FindResourceW",             (void *)FindResourceW             },
    { K32, "FindResourceA",             (void *)FindResourceA             },
    { K32, "FindResourceExW",           (void *)FindResourceExW           },
    { K32, "FindResourceExA",           (void *)FindResourceExA           },
    { K32, "LoadResource",              (void *)LoadResource              },
    { K32, "LockResource",              (void *)LockResource              },
    { K32, "SizeofResource",            (void *)SizeofResource            },
    { K32, "FreeResource",              (void *)FreeResource              },
    { K32, "LoadStringW",               (void *)LoadStringW               },
    { K32, "LoadStringA",               (void *)LoadStringA               },
    { K32, "EnumResourceNamesW",        (void *)EnumResourceNamesW        },
    { K32, "EnumResourceNamesA",        (void *)EnumResourceNamesA        },
    { U32, "FindResourceW",             (void *)FindResourceW             },
    { U32, "FindResourceA",             (void *)FindResourceA             },
    { U32, "FindResourceExW",           (void *)FindResourceExW           },
    { U32, "FindResourceExA",           (void *)FindResourceExA           },
    { U32, "LoadResource",              (void *)LoadResource              },
    { U32, "LockResource",              (void *)LockResource              },
    { U32, "SizeofResource",            (void *)SizeofResource            },
    { U32, "FreeResource",              (void *)FreeResource              },
    { U32, "LoadStringW",               (void *)LoadStringW               },
    { U32, "LoadStringA",               (void *)LoadStringA               },
    { U32, "LoadIconW",                 (void *)LoadIconW                 },
    { U32, "LoadIconA",                 (void *)LoadIconA                 },
    { U32, "LoadCursorW",               (void *)LoadCursorW               },
    { U32, "LoadCursorA",               (void *)LoadCursorA               },
    { U32, "LoadImageW",                (void *)LoadImageW                },
    { U32, "LoadImageA",                (void *)LoadImageA                },
    { U32, "DestroyIcon",               (void *)DestroyIcon               },
    { U32, "DestroyCursor",             (void *)DestroyCursor             },
    { U32, "EnumResourceNamesW",        (void *)EnumResourceNamesW        },
    { U32, "EnumResourceNamesA",        (void *)EnumResourceNamesA        },
    /* Dialogs */
    { U32, "DialogBoxParamW",           (void *)DialogBoxParamW           },
    { U32, "DialogBoxParamA",           (void *)DialogBoxParamA           },
    { U32, "DialogBoxIndirectParamW",   (void *)DialogBoxIndirectParamW   },
    { U32, "DialogBoxIndirectParamA",   (void *)DialogBoxIndirectParamA   },
    { U32, "DialogBoxW",                (void *)DialogBoxW                },
    { U32, "DialogBoxA",                (void *)DialogBoxA                },
    { U32, "EndDialog",                 (void *)EndDialog                 },
    { U32, "IsDialogMessageW",          (void *)IsDialogMessageW          },
    { U32, "IsDialogMessageA",          (void *)IsDialogMessageA          },
    { U32, "MapDialogRect",             (void *)MapDialogRect             },
    { U32, "GetDialogBaseUnits",        (void *)GetDialogBaseUnits        },
    { U32, "GetDlgItem",                (void *)GetDlgItem                },
    { U32, "GetDlgItemInt",             (void *)GetDlgItemInt             },
    { U32, "GetDlgItemTextW",           (void *)GetDlgItemTextW           },
    { U32, "GetDlgItemTextA",           (void *)GetDlgItemTextA           },
    { U32, "SetDlgItemInt",             (void *)SetDlgItemInt             },
    { U32, "SetDlgItemTextW",           (void *)SetDlgItemTextW           },
    { U32, "SetDlgItemTextA",           (void *)SetDlgItemTextA           },
    { U32, "IsDlgButtonChecked",        (void *)IsDlgButtonChecked        },
    { U32, "CheckDlgButton",            (void *)CheckDlgButton            },
    { U32, "CheckRadioButton",          (void *)CheckRadioButton          },
    /* Menus */
    { U32, "CreateMenu",                (void *)CreateMenu                },
    { U32, "CreatePopupMenu",           (void *)CreatePopupMenu           },
    { U32, "DestroyMenu",               (void *)DestroyMenu               },
    { U32, "AppendMenuW",               (void *)AppendMenuW               },
    { U32, "AppendMenuA",               (void *)AppendMenuA               },
    { U32, "InsertMenuW",               (void *)InsertMenuW               },
    { U32, "InsertMenuA",               (void *)InsertMenuA               },
    { U32, "TrackPopupMenu",            (void *)TrackPopupMenu            },
    { U32, "TrackPopupMenuEx",          (void *)TrackPopupMenuEx          },
    { U32, "GetMenu",                   (void *)GetMenu                   },
    { U32, "GetSubMenu",                (void *)GetSubMenu                },
    { U32, "GetSystemMenu",             (void *)GetSystemMenu             },
    { U32, "SetMenu",                   (void *)SetMenu                   },
    { U32, "CheckMenuItem",             (void *)CheckMenuItem             },
    { U32, "LoadMenuW",                 (void *)LoadMenuW                 },
    { U32, "LoadMenuA",                 (void *)LoadMenuA                 },
    { U32, "GetMenuItemCount",          (void *)GetMenuItemCount          },
    { U32, "GetMenuItemID",             (void *)GetMenuItemID             },
    { U32, "DrawMenuBar",               (void *)DrawMenuBar               },
    { U32, "RemoveMenu",                (void *)RemoveMenu                },
    { U32, "DeleteMenu",                (void *)DeleteMenu                },
    { U32, "EnableMenuItem",            (void *)EnableMenuItem            },
    { U32, "GetMenuBarInfo",            (void *)GetMenuBarInfo            },
    /* Timers */
    { U32, "SetTimer",                  (void *)SetTimer                  },
    { U32, "KillTimer",                 (void *)KillTimer                 },
    /* Caret */
    { U32, "CreateCaret",               (void *)CreateCaret               },
    { U32, "DestroyCaret",              (void *)DestroyCaret              },
    { U32, "SetCaretPos",               (void *)SetCaretPos               },
    { U32, "GetCaretPos",               (void *)GetCaretPos               },
    { U32, "ShowCaret",                 (void *)ShowCaret                 },
    { U32, "HideCaret",                 (void *)HideCaret                 },
    /* Accelerators */
    { U32, "LoadAcceleratorsW",         (void *)LoadAcceleratorsW         },
    { U32, "LoadAcceleratorsA",         (void *)LoadAcceleratorsA         },
    { U32, "TranslateAcceleratorW",     (void *)TranslateAcceleratorW     },
    { U32, "TranslateAcceleratorA",     (void *)TranslateAcceleratorA     },
    { U32, "DestroyAcceleratorTable",   (void *)DestroyAcceleratorTable   },
    { U32, "CreateAcceleratorTableW",   (void *)CreateAcceleratorTableW   },
    { U32, "CopyAcceleratorTableW",     (void *)CopyAcceleratorTableW     },
    /* Clipboard */
    { U32, "OpenClipboard",             (void *)OpenClipboard             },
    { U32, "CloseClipboard",            (void *)CloseClipboard            },
    { U32, "EmptyClipboard",            (void *)EmptyClipboard            },
    { U32, "SetClipboardData",          (void *)SetClipboardData          },
    { U32, "GetClipboardData",          (void *)GetClipboardData          },
    { U32, "IsClipboardFormatAvailable",(void *)IsClipboardFormatAvailable},
    { U32, "RegisterClipboardFormatW",  (void *)RegisterClipboardFormatW  },
    { U32, "RegisterClipboardFormatA",  (void *)RegisterClipboardFormatA  },
    { U32, "CountClipboardFormats",     (void *)CountClipboardFormats     },
    { U32, "EnumClipboardFormats",      (void *)EnumClipboardFormats      },
    { U32, "GetClipboardOwner",         (void *)GetClipboardOwner         },
    { U32, "GetOpenClipboardWindow",    (void *)GetOpenClipboardWindow    },
    { U32, "SetClipboardViewer",        (void *)SetClipboardViewer        },
    { U32, "ChangeClipboardChain",      (void *)ChangeClipboardChain      },
    { U32, "GetClipboardViewer",        (void *)GetClipboardViewer        },
    /* Hooks */
    { U32, "SetWindowsHookExW",         (void *)SetWindowsHookExW         },
    { U32, "SetWindowsHookExA",         (void *)SetWindowsHookExA         },
    { U32, "UnhookWindowsHookEx",       (void *)UnhookWindowsHookEx       },
    { U32, "CallNextHookEx",            (void *)CallNextHookEx            },
    /* DrawText + focus/edge/frame/icon/notify */
    { U32, "DrawTextW",                 (void *)DrawTextW                 },
    { U32, "DrawTextA",                 (void *)DrawTextA                 },
    { U32, "DrawTextExW",               (void *)DrawTextExW               },
    { U32, "DrawFocusRect",             (void *)DrawFocusRect             },
    { U32, "DrawEdge",                  (void *)DrawEdge                  },
    { U32, "DrawFrameControl",          (void *)DrawFrameControl          },
    { U32, "DrawIconEx",                (void *)DrawIconEx                },
    { U32, "DrawIcon",                  (void *)DrawIcon                  },
    { U32, "NotifyWinEvent",            (void *)NotifyWinEvent            },

    /* COMCTL32 (W32A-8).  The 27 ladder-measured symbols, all REAL in
     * w32/src/comctl32.c: the eight windowed controls (toolbar, status,
     * listview, treeview, tab, tooltip, progress, header -- real WC_*
     * classes driven through the SendMessage path with WM_NOTIFY to the
     * parent), PropertySheetW over the A-6 dialog engine, the ImageList
     * set including drag, the subclass ordinals 410-413, ordinal 381
     * (LoadIconWithScaleDown) and ordinal 17 (InitCommonControls).  The
     * UxTheme calls comctl32 v6 would make are stubbed until W32A-11
     * (recorded in the phase docs), and DllGetVersion / animation /
     * hotkey / datetime / monthcal / ipaddress / pager / nativetext are
     * deliberately absent: no ladder binary imports them. */
    { C32, "InitCommonControls",        (void *)InitCommonControls        },
    { C32, "InitCommonControlsEx",      (void *)InitCommonControlsEx      },
    { C32, "CreateToolbarEx",           (void *)CreateToolbarEx           },
    { C32, "CreateStatusWindowW",       (void *)CreateStatusWindowW       },
    { C32, "PropertySheetW",            (void *)PropertySheetW            },
    { C32, "LoadIconWithScaleDown",     (void *)LoadIconWithScaleDown     },
    { C32, "SetWindowSubclass",         (void *)SetWindowSubclass         },
    { C32, "RemoveWindowSubclass",      (void *)RemoveWindowSubclass      },
    { C32, "GetWindowSubclass",         (void *)GetWindowSubclass         },
    { C32, "DefSubclassProc",           (void *)DefSubclassProc           },
    { C32, "_TrackMouseEvent",          (void *)_TrackMouseEvent          },
    { C32, "ImageList_Create",          (void *)ImageList_Create          },
    { C32, "ImageList_Destroy",         (void *)ImageList_Destroy         },
    { C32, "ImageList_AddMasked",       (void *)ImageList_AddMasked       },
    { C32, "ImageList_ReplaceIcon",     (void *)ImageList_ReplaceIcon     },
    { C32, "ImageList_GetImageCount",   (void *)ImageList_GetImageCount   },
    { C32, "ImageList_GetIcon",         (void *)ImageList_GetIcon         },
    { C32, "ImageList_GetIconSize",     (void *)ImageList_GetIconSize     },
    { C32, "ImageList_GetImageInfo",    (void *)ImageList_GetImageInfo    },
    { C32, "ImageList_Draw",            (void *)ImageList_Draw            },
    { C32, "ImageList_SetIconSize",     (void *)ImageList_SetIconSize     },
    { C32, "ImageList_Remove",          (void *)ImageList_Remove          },
    { C32, "ImageList_BeginDrag",       (void *)ImageList_BeginDrag       },
    { C32, "ImageList_DragEnter",       (void *)ImageList_DragEnter       },
    { C32, "ImageList_DragMove",        (void *)ImageList_DragMove        },
    { C32, "ImageList_DragShowNolock",  (void *)ImageList_DragShowNolock  },
    { C32, "ImageList_EndDrag",         (void *)ImageList_EndDrag         },

    /* W32APP_PLAN.md W32A-9: advapi32.dll -- the registry (the W32HIVE1
     * engine, all REAL), the identity/SID/descriptor set (REAL against the
     * single-user model), the hash-only CryptoAPI over libatls (REAL;
     * SHA-1/MD5/SHA-384 refuse with NTE_BAD_ALGID, documented), RtlGenRandom
     * (SystemFunction036, REAL via getrandom), and the nine FAIL-CLEAN
     * finals implemented as final refusals with their documented codes --
     * there is no LSA, no account database, no token/privilege object and
     * no file ACL on the single-user machine.  RegFlushKey is not in any
     * ledger; it exists because the hive's fsync policy needs the
     * caller-visible flush point.  Nothing else beyond the ledger. */
    { A32, "RegOpenKeyExA",             (void *)RegOpenKeyExA             },
    { A32, "RegOpenKeyExW",             (void *)RegOpenKeyExW             },
    { A32, "RegCreateKeyExA",           (void *)RegCreateKeyExA           },
    { A32, "RegCreateKeyExW",           (void *)RegCreateKeyExW           },
    { A32, "RegCloseKey",               (void *)RegCloseKey               },
    { A32, "RegQueryValueExA",          (void *)RegQueryValueExA          },
    { A32, "RegQueryValueExW",          (void *)RegQueryValueExW          },
    { A32, "RegSetValueExA",            (void *)RegSetValueExA            },
    { A32, "RegSetValueExW",            (void *)RegSetValueExW            },
    { A32, "RegDeleteValueW",           (void *)RegDeleteValueW           },
    { A32, "RegDeleteKeyA",             (void *)RegDeleteKeyA             },
    { A32, "RegDeleteKeyW",             (void *)RegDeleteKeyW             },
    { A32, "RegDeleteKeyExW",           (void *)RegDeleteKeyExW           },
    { A32, "RegEnumKeyA",               (void *)RegEnumKeyA               },
    { A32, "RegEnumKeyExW",             (void *)RegEnumKeyExW             },
    { A32, "RegQueryInfoKeyW",          (void *)RegQueryInfoKeyW          },
    { A32, "RegGetValueW",              (void *)RegGetValueW              },
    { A32, "RegFlushKey",               (void *)RegFlushKey               },
    { A32, "GetUserNameA",              (void *)GetUserNameA              },
    { A32, "GetUserNameW",              (void *)GetUserNameW              },
    { A32, "AllocateAndInitializeSid",  (void *)AllocateAndInitializeSid  },
    { A32, "CopySid",                   (void *)CopySid                   },
    { A32, "EqualSid",                  (void *)EqualSid                  },
    { A32, "GetLengthSid",              (void *)GetLengthSid              },
    { A32, "FreeSid",                   (void *)FreeSid                   },
    { A32, "CheckTokenMembership",      (void *)CheckTokenMembership      },
    { A32, "InitializeSecurityDescriptor", (void *)InitializeSecurityDescriptor },
    { A32, "SetSecurityDescriptorDacl", (void *)SetSecurityDescriptorDacl },
    { A32, "SetSecurityDescriptorOwner", (void *)SetSecurityDescriptorOwner },
    { A32, "IsTextUnicode",             (void *)IsTextUnicode             },
    { A32, "CryptAcquireContextW",      (void *)CryptAcquireContextW      },
    { A32, "CryptReleaseContext",       (void *)CryptReleaseContext       },
    { A32, "CryptCreateHash",           (void *)CryptCreateHash           },
    { A32, "CryptHashData",             (void *)CryptHashData             },
    { A32, "CryptGetHashParam",         (void *)CryptGetHashParam         },
    { A32, "CryptDestroyHash",          (void *)CryptDestroyHash          },
    { A32, "SystemFunction036",         (void *)SystemFunction036         },
    { A32, "LsaOpenPolicy",             (void *)LsaOpenPolicy             },
    { A32, "LsaAddAccountRights",       (void *)LsaAddAccountRights       },
    { A32, "LsaClose",                  (void *)LsaClose                  },
    { A32, "LookupAccountNameW",        (void *)LookupAccountNameW        },
    { A32, "LookupPrivilegeValueW",     (void *)LookupPrivilegeValueW     },
    { A32, "OpenProcessToken",          (void *)OpenProcessToken          },
    { A32, "AdjustTokenPrivileges",     (void *)AdjustTokenPrivileges     },
    { A32, "GetFileSecurityW",          (void *)GetFileSecurityW          },
    { A32, "SetFileSecurityW",          (void *)SetFileSecurityW          },

    { 0, 0, 0 }
};

const w32_export_t *w32_exports(void) { return exports; }

void *w32_resolve(const char *dll, const char *name) {
    if (!dll || !name) return 0;
    for (const w32_export_t *e = exports; e->dll; e++) {
        if (!ieq(e->dll, dll)) continue;
        if (strcmp(e->name, name) == 0) return e->addr;
    }
    /* W32A-1: the generated table (TODO/FAILCLEAN stubs, data cells).  The
     * static table wins ties -- a real implementation always shadows the
     * stub it replaces, so behaviour phases cannot be masked by W32A-1. */
    for (const w32_export_t *e = w32_gen_exports(); e->dll; e++) {
        if (!ieq(e->dll, dll)) continue;
        if (strcmp(e->name, name) == 0) return e->addr;
    }
    return 0;
}

/* Write a 64-bit value into the mapped image.  The IAT is writable: the
 * loader maps .idata/.rdata per the section characteristics, and a PE that
 * marks its IAT read-only would fault here -- which is correct, and better
 * than silently mapping everything writable. */
static void poke64(uint64_t addr, uint64_t val) {
    uint8_t *p = (uint8_t *)(uintptr_t)addr;
    for (int i = 0; i < 8; i++) p[i] = (uint8_t)((val >> (i * 8)) & 0xFF);
}

int w32_bind_imports(const uint8_t *image, size_t image_size, uint64_t base,
                     const char **missing_dll, const char **missing_name) {
    /* Frame-local, NOT static: binding recurses (load_one -> map_dll ->
     * w32_bind_imports), and a shared array means the inner bind refills
     * what the outer loop is still reading -- the outer bind then
     * resolves the inner DLL's names and pokes the inner DLL's IAT RVAs
     * into its own image (W32A-1: chain_a's bind died on chain_b's
     * GetStdHandle).  256 entries x ~208 bytes x depth 8 fits any thread
     * stack several times over. */
    pe_import_t imports[256];
    /* The missings outlive the return (the caller prints them), so they
     * need stable storage of their own.  Single-flight: filled, then the
     * caller prints before any further bind -- like ordfmt below. */
    static char miss_dll[64], miss_name[128];
    pe_image_t img;
    size_t count = 0;

    if (missing_dll)  *missing_dll = 0;
    if (missing_name) *missing_name = 0;

    if (pe_parse(image, image_size, &img) != PE_OK) return -1;

    int rc = pe_imports(&img, imports, sizeof imports / sizeof imports[0], &count);
    if (rc != PE_OK) return -2;
    if (count == 0) return 0;                       /* nothing to bind */
    if (count > sizeof imports / sizeof imports[0]) return -3;

    for (size_t i = 0; i < count; i++) {
        pe_import_t *im = &imports[i];
        const char *name = im->name;
        static char ordfmt[16];

        /* Import by ordinal: the ordinal map names it (W32A-1), and the
         * name resolves like any other -- InitCommonControls answers to
         * both spellings, which is the plan's same-table alias.  Unknown
         * ordinals refuse BY NUMBER (D9), in the ledger's #<n> spelling. */
        if (im->by_ordinal) {
            const char *canon = w32_ordmap_lookup(im->dll, im->ordinal);
            if (!canon) {
                snprintf(ordfmt, sizeof ordfmt, "#%u", im->ordinal);
                snprintf(miss_dll, sizeof miss_dll, "%s", im->dll);
                if (missing_dll)  *missing_dll = miss_dll;
                if (missing_name) *missing_name = ordfmt;
                return -4;
            }
            name = canon;
        }

        /* Built-ins first (static, then generated stubs), then other user
         * DLLs, loaded recursively.  A dependency that will not load fails
         * the bind with the import named. */
        void *fn = w32_resolve(im->dll, name);
        if (!fn)
            fn = w32_load_dependency(im->dll, name, im->by_ordinal,
                                     im->ordinal);
        if (!fn) {
            snprintf(miss_dll, sizeof miss_dll, "%s", im->dll);
            snprintf(miss_name, sizeof miss_name, "%s", name);
            if (missing_dll)  *missing_dll = miss_dll;
            if (missing_name) *missing_name = miss_name;
            return -5;
        }
        poke64(base + im->iat_rva, (uint64_t)(uintptr_t)fn);
    }
    return 0;
}
