/* Generated by tools/w32_gen_stubs.py -- do not edit.
 * SPDX-License-Identifier: Apache-2.0 -- generated file, repository licence.
 *
 * W32A-1 loader tables: 15 ordinals, 782 stubs,
 * 3 data cells.  Sources: w32/ordinal_map.tsv (ordinal facts,
 * cited per row) and w32/stub_map.tsv (one row per ladder import the
 * static table in w32/src/w32_bind.c does not implement yet).
 *
 * A stub here is a bound address with an honest body: TODO stubs fail
 * loudly and name the phase that replaces them; FAILCLEAN stubs are the
 * final documented behaviour (mpr: no network provider).  Binding is not
 * behaviour (W32APP_PLAN.md W32A-1).
 */
#ifndef AURALITE_W32_GEN_H
#define AURALITE_W32_GEN_H

#include "w32/w32_bind.h"

/* Ordinal -> canonical name for one built-in module, or NULL when the
 * ordinal is unknown.  The caller resolves the NAME through the export
 * tables; an unknown ordinal refuses by number (D9). */
const char *w32_ordmap_lookup(const char *dll, unsigned ordinal);

/* The generated export table (TODO/FAILCLEAN/EXIT stubs + data cells),
 * NULL-terminated, same shape as w32_exports().  w32_resolve() falls
 * through to it after the static table. */
const w32_export_t *w32_gen_exports(void);

/* Bare module names the stub map covers ("kernel32", "mpr", ...),
 * NULL-terminated.  w32_module_init() registers each as a built-in so
 * GetModuleHandle/LoadLibrary find them; names already registered are
 * skipped, never duplicated. */
const char *const *w32_gen_modules(void);

#endif /* AURALITE_W32_GEN_H */
