#ifndef AURALITE_ARCH_X86_64_CPU_LOCAL_H
#define AURALITE_ARCH_X86_64_CPU_LOCAL_H

#include <stdint.h>
#include "kernel/lib/spinlock.h"

struct tcb;

struct cpu_local {
    struct cpu_local *self;       /* offset 0: GS:0 self-pointer */
    uint64_t          cpu_id;
    struct tcb       *current;
    struct tcb       *idle;

    /* Per-CPU run queue */
    spinlock_t        rq_lock;
    struct tcb       *rq_head;
    struct tcb       *rq_tail;
    uint32_t          rq_len;
    uint64_t          steal_count;

    /* Per-CPU SYSCALL entry state.  These slots used to be .data globals
     * inside syscall_entry.asm -- correct only while exactly one CPU could
     * ever enter the kernel, and silently corrupting each other the moment
     * two CPUs run syscalls concurrently.  The asm stub reaches them via
     * %gs: fixed offsets (generated by tools/gen_asm_offsets.c into
     * build/asm_offsets.inc); C code uses the syscall_saved_* accessor
     * macros in kernel/arch/x86_64/syscall.h.  A thread preempted mid-
     * syscall and resumed on another CPU is still safe: syscall_dispatch()
     * copies this frame into the TCB on entry, and
     * syscall_restore_user_frame() republishes it from the TCB into the
     * CURRENT cpu's slots right before sysret. */
    uint64_t          syscall_saved_rip;     /* user RIP (RCX at SYSCALL)    */
    uint64_t          syscall_saved_rflags;  /* user RFLAGS (R11 at SYSCALL) */
    uint64_t          syscall_saved_rsp;     /* user RSP                     */
    uint64_t          syscall_kernel_rsp;    /* per-thread kstack top        */
    uint64_t          syscall_saved_rbx;
    uint64_t          syscall_saved_rbp;
    uint64_t          syscall_saved_r12;
    uint64_t          syscall_saved_r13;
    uint64_t          syscall_saved_r14;
    uint64_t          syscall_saved_r15;

    /* Per-CPU "current address space" pointer for the VMM (HHDM virtual
     * pointer to the PML4 this CPU's CR3 currently selects).  Until SMP
     * step 3.2 the VMM kept this in a single global in paging.c, which two
     * CPUs running threads with different address spaces would overwrite
     * under each other; paging_switch_to() now updates THIS slot (written
     * by the scheduler on the CPU that actually switches CR3).  Zero means
     * "fall back to the kernel's boot PML4" (early boot / kernel threads).
     * Appended at the END of the struct so the %gs: syscall offsets baked
     * into syscall_entry.asm (build/asm_offsets.inc) do not shift. */
    uint64_t          vm_pml4;
};

void cpu_local_init(uint64_t cpu_id);

extern int cpu_local_ready;
extern struct cpu_local bsp_cpu_local;
extern struct cpu_local ap_cpu_locals[32];

static inline struct cpu_local *get_cpu_local(void) {
    struct cpu_local *p;
    __asm__ volatile ("mov %%gs:0, %0" : "=r"(p));
    return p;
}

#endif /* AURALITE_ARCH_X86_64_CPU_LOCAL_H */