#!/usr/bin/env python3
"""extract_libc_impls.py — DOOM_PLAN.md D1.

Extracts AuraLite's memmove(), abs() and vsnprintf() into standalone files
for tests/unit/, renaming them to auralite_*.

Why extract rather than #include the .c files: string_extra.c and
stdlib_extra.c include AuraLite's own headers, which conflict with the
host's on a host build.

Why rename: GCC treats memmove() and abs() as builtins and replaces calls
to them with its own expansion, so a test calling them by their standard
names never reaches the code under test. That was not a hypothesis -- it
was caught by mutation testing, where breaking memmove's direction check
changed nothing until the calls were renamed.
"""
import re
import sys


def extract(path, signature, newname):
    src = open(path).read()
    i = src.find(signature)
    if i < 0:
        print(f"extract_libc_impls: {signature!r} not found in {path}",
              file=sys.stderr)
        sys.exit(1)
    end = src.index("\n}\n", i) + 3
    body = src[i:end]
    # Rename only the definition's own name, not calls inside it.
    return body.replace(signature, signature.replace(
        re.match(r"\w+[ *]+(\w+)", signature).group(1), newname, 1), 1)


def extract_printf(path):
    """The formatter is a block of statics plus vsnprintf, not one function.

    Taken as a span from the sink struct to the end of vsnprintf so that the
    helpers travel with it.  Only vsnprintf is renamed; the statics are
    file-local and cannot clash with the host's.
    """
    src = open(path).read()
    i = src.index("struct fmt_sink {")
    j = src.index("int vsnprintf(char *str, size_t size, const char *fmt, va_list ap) {")
    k = src.index("\n}\n", src.index("return", j)) + 3
    return src[i:k].replace("int vsnprintf(", "int auralite_vsnprintf(", 1)


def main():
    if len(sys.argv) != 2:
        print("usage: extract_libc_impls.py <out.c>", file=sys.stderr)
        return 2
    out = ["/* Generated by tools/extract_libc_impls.py -- do not edit. */",
           "#include <stddef.h>", ""]
    out.append(extract("lib/libc/src/string_extra.c",
                       "void *memmove(void *dst, const void *src, size_t n) {",
                       "auralite_memmove"))
    out.append(extract("lib/libc/src/stdlib_extra.c",
                       "int abs(int v) {", "auralite_abs"))

    # The printf formatter, for test_printf_format.c.
    out[1] = "#include <stddef.h>\n#include <stdint.h>\n#include <stdarg.h>"
    out.append("/* strnlen() is used by the %s path; the host has it in "
               "<string.h>, which\n * this file deliberately does not "
               "include. */")
    # __attribute__((unused)): this file is shared by both unit tests and
    # test_stdio_seek.c does not pull in the %s path, so the helper is dead
    # code there -- and both tests build with -Werror.
    out.append("__attribute__((unused))\n"
               "static size_t aura_strnlen(const char *s, size_t m) "
               "{ size_t n = 0; while (n < m && s[n]) n++; return n; }")
    out.append("#define strnlen aura_strnlen")
    out.append(extract_printf("lib/libc/src/libc.c"))
    out.append("""
int auralite_snprintf(char *b, size_t n, const char *f, ...) {
    va_list ap;
    va_start(ap, f);
    int r = auralite_vsnprintf(b, n, f, ap);
    va_end(ap);
    return r;
}
""")
    open(sys.argv[1], "w").write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
