#!/usr/bin/env python3
"""extract_libc_impls.py — DOOM_PLAN.md D1.

Extracts AuraLite's memmove(), abs() and vsnprintf() into standalone files
for tests/unit/, renaming them to auralite_*.

Why extract rather than #include the .c files: string_extra.c and
stdlib_extra.c include AuraLite's own headers, which conflict with the
host's on a host build.

Why rename: GCC treats memmove() and abs() as builtins and replaces calls
to them with its own expansion, so a test calling them by their standard
names never reaches the code under test. That was not a hypothesis -- it
was caught by mutation testing, where breaking memmove's direction check
changed nothing until the calls were renamed.
"""
import re
import sys


def extract(path, signature, newname, rewrites=None):
    src = open(path).read()
    i = src.find(signature)
    if i < 0:
        print(f"extract_libc_impls: {signature!r} not found in {path}",
              file=sys.stderr)
        sys.exit(1)
    end = src.index("\n}\n", i) + 3
    body = src[i:end]
    # Rename only the definition's own name, not calls inside it.
    body = body.replace(signature, signature.replace(
        re.match(r"\w+[ *]+(\w+)", signature).group(1), newname, 1), 1)
    # RESIDUE2 T4 (math review): optional in-body call rewrites so an
    # extracted kernel keeps calling its EXTRACTED dependencies (pow must
    # call a_exp/a_log, not glibc's) -- otherwise the review would measure
    # the host's math wearing our names.
    for old, new in (rewrites or []):
        body = body.replace(old, new)
    return body


def extract_printf(path):
    """The formatter is a block of statics plus vsnprintf, not one function.

    Taken as a span from the sink struct to the end of vsnprintf so that the
    helpers travel with it.  Only vsnprintf is renamed; the statics are
    file-local and cannot clash with the host's.
    """
    src = open(path).read()
    i = src.index("struct fmt_sink {")
    j = src.index("int vsnprintf(char *str, size_t size, const char *fmt, va_list ap) {")
    k = src.index("\n}\n", src.index("return", j)) + 3
    return src[i:k].replace("int vsnprintf(", "int auralite_vsnprintf(", 1)


def math_review(out_path):
    """RESIDUE2 T4: the libm kernels for tests/unit/test_mathulp.c.

    Extracts the shipping sin/cos/exp/log/pow/sqrt/fmod (libc.c) and
    asin/acos (math_extra.c) with a_* names, rewriting in-body calls
    so the dependency edges stay in-tree: pow -> a_exp/a_log, sin/cos ->
    a_fmod, acos -> a_asin.  asin's atan/sqrt resolve to the HOST's on
    purpose: the ULP grids do not cover asin/acos (their kernel is atan,
    unchanged by T4); the extracted bodies exist for the errno contract
    test, where glibc's atan/sqrt are equivalent inputs.
    """
    out = ["/* Generated by tools/extract_libc_impls.py --math-review"
           " -- do not edit. */",
           "#include <math.h>",
           "#include <errno.h>",
           "#ifndef M_PI",
           "#define M_PI 3.14159265358979323846",
           "#endif",
           "#ifndef M_PI_2",
           "#define M_PI_2 (M_PI / 2.0)",
           "#endif",
           "double a_fmod(double x, double y);",
           "double a_asin(double x);",
           "/* math_extra.c's file-static helper, reproduced for the"
           " extracted bodies. */",
           "static int is_nan(double x) { return x != x; }",
           ""]
    libc = "lib/libc/src/libc.c"
    mex = "lib/libc/src/math_extra.c"
    out.append(extract(libc, "double sqrt(double x) {", "a_sqrt"))
    out.append(extract(libc, "double exp(double x) {", "a_exp"))
    out.append(extract(libc, "double log(double x) {", "a_log"))
    out.append(extract(libc, "double pow(double base, double e) {", "a_pow",
                       rewrites=[("exp(", "a_exp("), ("log(", "a_log(")]))
    out.append(extract(libc, "double sin(double x) {", "a_sin",
                       rewrites=[("fmod(", "a_fmod(")]))
    out.append(extract(libc, "double cos(double x) {", "a_cos",
                       rewrites=[("fmod(", "a_fmod(")]))
    out.append(extract(libc, "double fmod(double x, double y) {", "a_fmod"))
    out.append(extract(mex, "double asin(double x) {", "a_asin"))
    out.append(extract(mex, "double acos(double x) {", "a_acos",
                       rewrites=[("asin(", "a_asin(")]))
    open(out_path, "w").write("\n".join(out))


def main():
    if len(sys.argv) == 3 and sys.argv[1] == "--math-review":
        return math_review(sys.argv[2])
    if len(sys.argv) != 2:
        print("usage: extract_libc_impls.py <out.c> | "
              "extract_libc_impls.py --math-review <out.c>",
              file=sys.stderr)
        return 2
    out = ["/* Generated by tools/extract_libc_impls.py -- do not edit. */",
           "#include <stddef.h>", ""]
    out.append(extract("lib/libc/src/string_extra.c",
                       "void *memmove(void *dst, const void *src, size_t n) {",
                       "auralite_memmove"))
    # SELFHOST SH5d added memchr() so aulink's merge-pool scan can find string
    # terminators inside raw ELF sections without dragging in posix_extra.c.
    # Extracted (not re-implemented) and renamed for the same reason as
    # memmove: GCC expands a call to plain memchr() into its own builtin, so
    # a test calling it by name would never reach the shipped code.
    out.append(extract("lib/libc/src/string_extra.c",
                       "void *memchr(const void *src, int c, size_t n) {",
                       "auralite_memchr"))
    out.append(extract("lib/libc/src/stdlib_extra.c",
                       "int abs(int v) {", "auralite_abs"))

    # The printf formatter, for test_printf_format.c.
    out[1] = "#include <stddef.h>\n#include <stdint.h>\n#include <stdarg.h>"
    out.append("/* strnlen() is used by the %s path; the host has it in "
               "<string.h>, which\n * this file deliberately does not "
               "include. */")
    # __attribute__((unused)): this file is shared by both unit tests and
    # test_stdio_seek.c does not pull in the %s path, so the helper is dead
    # code there -- and both tests build with -Werror.
    out.append("__attribute__((unused))\n"
               "static size_t aura_strnlen(const char *s, size_t m) "
               "{ size_t n = 0; while (n < m && s[n]) n++; return n; }")
    out.append("#define strnlen aura_strnlen")
    out.append(extract_printf("lib/libc/src/libc.c"))
    out.append("""
int auralite_snprintf(char *b, size_t n, const char *f, ...) {
    va_list ap;
    va_start(ap, f);
    int r = auralite_vsnprintf(b, n, f, ap);
    va_end(ap);
    return r;
}
""")
    open(sys.argv[1], "w").write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
