#!/usr/bin/env python3
"""Generate userspace/apps/gbrowser/wv_cp1251_font.inc — 128 glyphs × 16
bytes (codepoints 0x80–0xFF as windows-1251) from DejaVu Sans Mono.

ASCII 0x00–0x7F stays the VGA PSF2 blob; this overlay is only the high
half so gbrowser can paint Russian Google (CP1251) and mapped UTF-8.
"""
from __future__ import annotations

import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "userspace", "apps", "gbrowser", "wv_cp1251_font.inc")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

# windows-1251 → Unicode for 0x80–0xBF; 0xC0–0xFF is А–я (U+0410+).
CP1251_LOW = {
    0x80: 0x0402, 0x81: 0x0403, 0x82: 0x201A, 0x83: 0x0453, 0x84: 0x201E,
    0x85: 0x2026, 0x86: 0x2020, 0x87: 0x2021, 0x88: 0x20AC, 0x89: 0x2030,
    0x8A: 0x0409, 0x8B: 0x2039, 0x8C: 0x040A, 0x8D: 0x040C, 0x8E: 0x040B,
    0x8F: 0x040F, 0x90: 0x0452, 0x91: 0x2018, 0x92: 0x2019, 0x93: 0x201C,
    0x94: 0x201D, 0x95: 0x2022, 0x96: 0x2013, 0x97: 0x2014, 0x98: 0x0000,
    0x99: 0x2122, 0x9A: 0x0459, 0x9B: 0x203A, 0x9C: 0x045A, 0x9D: 0x045C,
    0x9E: 0x045B, 0x9F: 0x045F, 0xA0: 0x00A0, 0xA1: 0x040E, 0xA2: 0x045E,
    0xA3: 0x0408, 0xA4: 0x00A4, 0xA5: 0x0490, 0xA6: 0x00A6, 0xA7: 0x00A7,
    0xA8: 0x0401, 0xA9: 0x00A9, 0xAA: 0x0404, 0xAB: 0x00AB, 0xAC: 0x00AC,
    0xAD: 0x00AD, 0xAE: 0x00AE, 0xAF: 0x0407, 0xB0: 0x00B0, 0xB1: 0x00B1,
    0xB2: 0x0406, 0xB3: 0x0456, 0xB4: 0x0491, 0xB5: 0x00B5, 0xB6: 0x00B6,
    0xB7: 0x00B7, 0xB8: 0x0451, 0xB9: 0x2116, 0xBA: 0x0454, 0xBB: 0x00BB,
    0xBC: 0x0458, 0xBD: 0x0405, 0xBE: 0x0455, 0xBF: 0x0457,
}


def cp1251_to_uni(b: int) -> int:
    if 0xC0 <= b <= 0xFF:
        return 0x0410 + (b - 0xC0)
    return CP1251_LOW.get(b, 0)


def render_glyph(font: ImageFont.FreeTypeFont, cp: int) -> list[int]:
    img = Image.new("L", (8, 16), 0)
    if cp == 0:
        return [0] * 16
    ch = chr(cp)
    draw = ImageDraw.Draw(img)
    # Anchor at a VGA-like baseline so Cyrillic sits on the same line as ASCII.
    try:
        bbox = font.getbbox(ch)
    except Exception:
        bbox = (0, 0, 8, 12)
    gw = max(1, bbox[2] - bbox[0])
    gh = max(1, bbox[3] - bbox[1])
    x = max(-2, (8 - gw) // 2 - bbox[0])
    # Prefer sitting on row 12 (VGA baseline-ish); clamp into the cell.
    y = 12 - bbox[3]
    if y + bbox[1] < 0:
        y = -bbox[1]
    if y + bbox[3] > 16:
        y = 16 - bbox[3]
    draw.text((x, y), ch, font=font, fill=255)
    rows = []
    for row in range(16):
        bits = 0
        for col in range(8):
            if img.getpixel((col, row)) >= 96:
                bits |= 0x80 >> col
        rows.append(bits)
    return rows


def main() -> None:
    font = ImageFont.truetype(FONT, 11)
    lines = [
        "/* wv_cp1251_font.inc — 8×16 glyphs for windows-1251 0x80–0xFF.",
        " * Auto-generated by tools/gen_wv_cp1251_font.py from DejaVu Sans Mono.",
        " * ASCII 0x00–0x7F stays the VGA PSF2 blob in wv_paint.c.",
        " */",
        "static const unsigned char wv_cp1251_font[128 * 16] = {",
    ]
    for b in range(0x80, 0x100):
        rows = render_glyph(font, cp1251_to_uni(b))
        hexes = ", ".join(f"0x{r:02x}" for r in rows)
        uni = cp1251_to_uni(b)
        label = "-" if uni == 0 else chr(uni)
        lines.append(f"    {hexes},  /* 0x{b:02X} {label} */")
    lines.append("};")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
