/* gen_user_binary.c -- convert an ELF file into the C array the kernel's
 * embedded-user-program loader consumes.
 *
 * This is the freestanding-C replacement for gen_user_binary.py.  Keeping
 * the generator in C matters for SELFHOST_PLAN.md SH5d: AuraLite can build
 * and run it with its own tcc/libc while preparing the next kernel, without
 * asking the host for Python.
 *
 * Usage: gen_user_binary <input.elf> <output.h> <symbol_name>
 */

#include <stdio.h>
#include <stdlib.h>

static int fail(const char *what, const char *path)
{
    fprintf(stderr, "gen_user_binary: %s '%s'\n", what, path ? path : "");
    return 1;
}

int main(int argc, char **argv)
{
    const char *input;
    const char *output;
    const char *symbol;
    FILE *in;
    FILE *out;
    long length;
    unsigned char bytes[16];
    size_t got;

    if (argc != 4) {
        fprintf(stderr,
                "usage: gen_user_binary <input.elf> <output.h> <symbol_name>\n");
        return 2;
    }
    input = argv[1];
    output = argv[2];
    symbol = argv[3];

    in = fopen(input, "rb");
    if (!in) return fail("cannot open", input);
    if (fseek(in, 0, SEEK_END) != 0 || (length = ftell(in)) < 0 ||
        fseek(in, 0, SEEK_SET) != 0) {
        fclose(in);
        return fail("cannot size", input);
    }

    out = fopen(output, "wb");
    if (!out) {
        fclose(in);
        return fail("cannot create", output);
    }

    fprintf(out, "/* Auto-generated by tools/gen_user_binary.c. Do not edit. */\n");
    fprintf(out, "/* Source: %s (%lu bytes) */\n\n", input,
            (unsigned long)length);
    fprintf(out, "const unsigned char %s[%lu] = {\n", symbol,
            (unsigned long)length);

    while ((got = fread(bytes, 1, sizeof(bytes), in)) != 0) {
        for (size_t i = 0; i < got; i++) {
            if (i != 0) fputs(", ", out);
            fprintf(out, "0x%02x", (unsigned)bytes[i]);
        }
        fputs(",\n", out);
    }

    fputs("};\n", out);
    fprintf(out, "const unsigned long %s_size = %lu;\n", symbol,
            (unsigned long)length);
    fclose(out);
    fclose(in);
    return 0;
}
