/* tools/gen_asm_offsets.c — emit nasm %defines for struct field offsets.
 *
 * Hardcoding TCB field offsets in hand-written assembly (context.asm) is
 * extremely fragile: any change to tcb_t silently corrupts context switches.
 * This generator computes the offsets at build time and writes a nasm include
 * so the assembly always matches the C struct layout.
 *
 * Usage: gen_asm_offsets > build/asm_offsets.inc
 */

#include <stddef.h>
#include <stdio.h>
#include "kernel/proc/thread.h"

int main(void) {
    printf("; AUTO-GENERATED by tools/gen_asm_offsets.c — do not edit.\n");
    printf("%%define TCB_RSP      %zu\n", offsetof(tcb_t, rsp));
    printf("%%define TCB_TLS_BASE %zu\n", offsetof(tcb_t, tls_base));
    printf("%%define TCB_PML4     %zu\n", offsetof(tcb_t, pml4_phys));
    printf("%%define TCB_SIZE     %zu\n", sizeof(tcb_t));
    return 0;
}
