/* tools/gen_asm_offsets.c — emit nasm %defines for struct field offsets.
 *
 * Hardcoding TCB field offsets in hand-written assembly (context.asm) is
 * extremely fragile: any change to tcb_t silently corrupts context switches.
 * The same applies to struct cpu_local slots that syscall_entry.asm reads
 * through %gs.  This generator computes the offsets at build time and
 * writes a nasm include so the assembly always matches the C struct layout.
 *
 * Usage: gen_asm_offsets > build/asm_offsets.inc
 */

#include <stddef.h>
#include <stdio.h>
#include "kernel/proc/thread.h"
#include "kernel/arch/x86_64/cpu_local.h"

int main(void) {
    printf("; AUTO-GENERATED by tools/gen_asm_offsets.c — do not edit.\n");
    printf("%%define TCB_RSP      %zu\n", offsetof(tcb_t, rsp));
    printf("%%define TCB_TLS_BASE %zu\n", offsetof(tcb_t, tls_base));
    printf("%%define TCB_PML4     %zu\n", offsetof(tcb_t, pml4_phys));
    printf("%%define TCB_SIZE     %zu\n", sizeof(tcb_t));

    /* struct cpu_local SYSCALL-entry slots (reached via %gs: in
     * syscall_entry.asm). */
    printf("%%define CL_SYS_RIP    %zu\n",
           offsetof(struct cpu_local, syscall_saved_rip));
    printf("%%define CL_SYS_RFLAGS %zu\n",
           offsetof(struct cpu_local, syscall_saved_rflags));
    printf("%%define CL_SYS_RSP    %zu\n",
           offsetof(struct cpu_local, syscall_saved_rsp));
    printf("%%define CL_SYS_KRSP   %zu\n",
           offsetof(struct cpu_local, syscall_kernel_rsp));
    printf("%%define CL_SYS_RBX    %zu\n",
           offsetof(struct cpu_local, syscall_saved_rbx));
    printf("%%define CL_SYS_RBP    %zu\n",
           offsetof(struct cpu_local, syscall_saved_rbp));
    printf("%%define CL_SYS_R12    %zu\n",
           offsetof(struct cpu_local, syscall_saved_r12));
    printf("%%define CL_SYS_R13    %zu\n",
           offsetof(struct cpu_local, syscall_saved_r13));
    printf("%%define CL_SYS_R14    %zu\n",
           offsetof(struct cpu_local, syscall_saved_r14));
    printf("%%define CL_SYS_R15    %zu\n",
           offsetof(struct cpu_local, syscall_saved_r15));
    return 0;
}
