/* tools/gen_boot_offsets.c -- emit boot_info_t offsets for assembly and tests.
 *
 * BIOS Stage 2 writes boot_info_t fields from hand-written assembly.  Numeric
 * offsets in that assembly are fragile: a C struct layout change would silently
 * move fields while Stage 2 kept writing the old offsets.  This host tool uses
 * offsetof() against the real boot/shared/boot_info.h definition and emits the
 * constants consumed by NASM and by host-side unit tests.
 *
 * Usage:
 *   gen_boot_offsets --asm > build/boot_offsets.inc
 *   gen_boot_offsets --c   > build/boot_offsets.h
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "boot/shared/boot_info.h"

struct offset_entry {
    const char *name;
    size_t value;
};

#define ENTRY(name, field) { name, offsetof(boot_info_t, field) }

static const struct offset_entry offsets[] = {
    ENTRY("BOOT_MAGIC_OFF", magic),
    ENTRY("BOOT_FB_OFF", fb),
    ENTRY("BOOT_MMAP_OFF", mmap),
    ENTRY("BOOT_MMAP_CNT_OFF", mmap_count),
    ENTRY("BOOT_HHDM_OFF", hhdm_offset),
    ENTRY("BOOT_INITRD_P_OFF", initrd_phys),
    ENTRY("BOOT_INITRD_S_OFF", initrd_size),
    ENTRY("BOOT_CPUCNT_OFF", cpu_count),
    ENTRY("BOOT_BSP_LAPIC_OFF", bsp_lapic_id),
    ENTRY("BOOT_CPUS_OFF", cpus),
    ENTRY("BOOT_RSDP_OFF", rsdp_phys),
    ENTRY("BOOT_UEFI_OFF", boot_from_uefi),
};

static void emit_asm(void) {
    puts("; Auto-generated by tools/gen_boot_offsets.c -- DO NOT EDIT.");
    puts("; Run 'make boot-offsets' to regenerate.");
    for (size_t i = 0; i < sizeof(offsets) / sizeof(offsets[0]); i++) {
        printf("%%define %-20s %zu\n", offsets[i].name, offsets[i].value);
    }
    printf("%%define %-20s %zu\n", "BOOT_INFO_SIZEOF", sizeof(boot_info_t));
}

static void emit_c(void) {
    puts("/* Auto-generated by tools/gen_boot_offsets.c -- DO NOT EDIT. */");
    puts("/* Run 'make boot-offsets' to regenerate. */");
    puts("#ifndef AURALITE_BUILD_BOOT_OFFSETS_H");
    puts("#define AURALITE_BUILD_BOOT_OFFSETS_H");
    puts("");
    for (size_t i = 0; i < sizeof(offsets) / sizeof(offsets[0]); i++) {
        printf("#define %s_C %zuULL\n", offsets[i].name, offsets[i].value);
    }
    printf("#define BOOT_INFO_SIZEOF_C %zuULL\n", sizeof(boot_info_t));
    puts("");
    puts("#endif /* AURALITE_BUILD_BOOT_OFFSETS_H */");
}

int main(int argc, char **argv) {
    if (argc == 1 || strcmp(argv[1], "--asm") == 0) {
        emit_asm();
        return 0;
    }
    if (strcmp(argv[1], "--c") == 0) {
        emit_c();
        return 0;
    }

    fprintf(stderr, "usage: %s [--asm|--c]\n", argv[0]);
    return 2;
}
