#!/usr/bin/env python3
"""gen_user_binary.py — convert a compiled ELF binary to a C header array.

Usage: gen_user_binary.py <input.elf> <output.h> <symbol_name>
The generated header defines `extern const unsigned char <symbol_name>[]` and
`extern const unsigned long <symbol_name>_size`, which the kernel's ELF loader
reads to parse and map the user program.
"""
import sys

if len(sys.argv) != 4:
    sys.exit("usage: gen_user_binary.py <input.elf> <output.h> <symbol_name>")

inp, outp, sym = sys.argv[1], sys.argv[2], sys.argv[3]

with open(inp, "rb") as f:
    data = f.read()

with open(outp, "w") as f:
    f.write("/* Auto-generated by tools/gen_user_binary.py. Do not edit. */\n")
    f.write(f"/* Source: {inp} ({len(data)} bytes) */\n\n")
    f.write(f"const unsigned char {sym}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        f.write(f"    {hex_bytes},\n")
    f.write("};\n")
    f.write(f"const unsigned long {sym}_size = {len(data)};\n")
