/* tools/gen_asm_offsets.c — emit nasm %defines for struct field offsets.
 *
 * Hardcoding TCB field offsets in hand-written assembly (context.asm) is
 * extremely fragile: any change to tcb_t silently corrupts context switches.
 * The same applies to struct cpu_local slots that syscall_entry.asm reads
 * through %gs.  This generator computes the offsets at build time and
 * writes a nasm include so the assembly always matches the C struct layout.
 *
 * Usage: gen_asm_offsets [build/asm_offsets.inc]
 *
 * With no argument this keeps the original stdout contract.  An output path
 * avoids a shell redirection in AuraLite's SH5d in-guest build.
 *
 * Both forms emit BYTE-IDENTICAL text, including the two hand-tuned column
 * widths the assembly has always been generated with: 13 columns for the
 * TCB_RSP..TCB_SWITCH_PARKED block, 14 for TCB_FPU, TCB_FPU_VALID and the
 * CL_SYS_ slots.  Keeping the bytes stable means build/asm_offsets.inc does
 * not churn on an unrelated refactor, so a diff in it always means a real
 * struct-layout change.
 */

#include <stddef.h>
#include <stdio.h>
#include "kernel/proc/thread.h"
#include "kernel/arch/x86_64/cpu_local.h"

/* Name field padded to 12 columns, then one space. */
#define EMIT_OFFSET(f, name, type, member) \
    fprintf((f), "%%define %-12s %lu\n", (name), \
            (unsigned long)offsetof(type, member))

/* Name field padded to 13 columns, then one space -- the wider block. */
#define EMIT_OFFSET_W(f, name, type, member) \
    fprintf((f), "%%define %-13s %lu\n", (name), \
            (unsigned long)offsetof(type, member))

static int emit_offsets(FILE *out) {
    fprintf(out, "; AUTO-GENERATED by tools/gen_asm_offsets.c — do not edit.\n");
    EMIT_OFFSET(out, "TCB_RSP",      tcb_t, rsp);
    EMIT_OFFSET(out, "TCB_TLS_BASE", tcb_t, tls_base);
    EMIT_OFFSET(out, "TCB_PML4",     tcb_t, pml4_phys);
    fprintf(out, "%%define %-12s %lu\n", "TCB_SIZE", (unsigned long)sizeof(tcb_t));
    /* SMP step 3.2 parking flag: context_switch() sets this right after the
     * final save completes (see thread.h / scheduler.c). */
    EMIT_OFFSET(out, "TCB_SWITCH_PARKED", tcb_t, switch_parked);
    /* M1 (MATURITY_PLAN.md): FPU/SSE context-save area + validity flag, used
     * by context_switch()'s eager fxsave/fxrstor.  fpu_area is aligned(16). */
    EMIT_OFFSET_W(out, "TCB_FPU",       tcb_t, fpu_area);
    EMIT_OFFSET_W(out, "TCB_FPU_VALID", tcb_t, fpu_valid);

    /* struct cpu_local SYSCALL-entry slots (reached via %gs: in
     * syscall_entry.asm). */
    EMIT_OFFSET_W(out, "CL_SYS_RIP",    struct cpu_local, syscall_saved_rip);
    EMIT_OFFSET_W(out, "CL_SYS_RFLAGS", struct cpu_local, syscall_saved_rflags);
    EMIT_OFFSET_W(out, "CL_SYS_RSP",    struct cpu_local, syscall_saved_rsp);
    EMIT_OFFSET_W(out, "CL_SYS_KRSP",   struct cpu_local, syscall_kernel_rsp);
    EMIT_OFFSET_W(out, "CL_SYS_RBX",    struct cpu_local, syscall_saved_rbx);
    EMIT_OFFSET_W(out, "CL_SYS_RBP",    struct cpu_local, syscall_saved_rbp);
    EMIT_OFFSET_W(out, "CL_SYS_R12",    struct cpu_local, syscall_saved_r12);
    EMIT_OFFSET_W(out, "CL_SYS_R13",    struct cpu_local, syscall_saved_r13);
    EMIT_OFFSET_W(out, "CL_SYS_R14",    struct cpu_local, syscall_saved_r14);
    EMIT_OFFSET_W(out, "CL_SYS_R15",    struct cpu_local, syscall_saved_r15);

    /* A truncated include would assemble into a kernel with wrong field
     * offsets, which fails at runtime rather than at build time -- so a
     * write error here has to be an error here. */
    return ferror(out) ? 1 : 0;
}

int main(int argc, char **argv) {
    FILE *out = stdout;
    int rc;

    if (argc > 2) {
        fprintf(stderr, "usage: gen_asm_offsets [output.inc]\n");
        return 2;
    }
    if (argc == 2) {
        out = fopen(argv[1], "wb");
        if (!out) {
            fprintf(stderr, "gen_asm_offsets: cannot create '%s'\n", argv[1]);
            return 1;
        }
    }

    rc = emit_offsets(out);
    if (out != stdout) {
        if (fclose(out) != 0) rc = 1;
    }
    return rc;
}
