#!/usr/bin/env python3
"""Generate the W32A-1 loader tables from w32/stub_map.tsv + ordinal_map.tsv.

Second level of the W32A-1 pipeline (see tools/w32_mkstubmap.py): pure
python + committed TSV in, C out.  No mingw, no network, no clock -- the
claim checker re-runs this byte-for-byte, so anything non-deterministic
here fails the build.  Keep it that way.

Outputs:
  w32/src/w32_stubs_gen.c      ordinal table, stubs, data cells,
                               generated export table, module list
  w32/include/w32/w32_gen.h     the three accessors w32_bind.c/w32_module.c use

Stub kinds (from the TSV):
  TODO      logs once ("needs W32A-N"), sets ERROR_NOT_SUPPORTED, fails
            with the row's value.  A behaviour phase replaces the stub
            and flips the row's kind; until then the failure is loud.
  FAILCLEAN final W32A-1 fail-clean (mpr): logs once with the reason,
            returns the documented code directly.  No last-error games:
            WNet* returns the code itself.
  EXIT      one-arg stub that really terminates via ExitProcess.  A (void)
            stub would resume AFTER exit, which is the one failure shape
            worse than a loud TODO.
  DATA      a zeroed BSS cell of the row's size.  The loader binds the
            import to its address; nothing ever calls it.
  REAL      hand implementation elsewhere; nothing emitted.  The checker
            asserts the symbol resolves from the static table instead.

Usage:
    python3 tools/w32_gen_stubs.py [--check]
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STUBMAP = os.path.join(ROOT, "w32", "stub_map.tsv")
ORDMAP = os.path.join(ROOT, "w32", "ordinal_map.tsv")
OUT_C = os.path.join(ROOT, "w32", "src", "w32_stubs_gen.c")
OUT_H = os.path.join(ROOT, "w32", "include", "w32", "w32_gen.h")

# Win32 codes the generator names rather than inlining (all defined in
# w32/w32_errno.h; anything else is emitted as a literal with a comment,
# which is deliberately ugly so it gets a name).
CODE_NAMES = {
    "1222": "W32_ERROR_NO_NETWORK",
    "259": "W32_ERROR_NO_MORE_ITEMS",
    "6": "W32_ERROR_INVALID_HANDLE",
}

P64_TYPES = {
    "HANDLE", "HWND", "HDC", "HBITMAP", "HBRUSH", "HFONT", "HICON",
    "HCURSOR", "HMENU", "HPEN", "HPALETTE", "HRGN", "HINSTANCE",
    "HMODULE", "HIMAGELIST", "HIMC", "HHOOK", "HACCEL", "HCERTSTORE",
    "HCRYPTPROV", "HCRYPTKEY", "HCRYPTHASH", "LPVOID", "LRESULT",
    "LPARAM", "WPARAM", "LONG_PTR", "ULONG_PTR", "DWORD_PTR",
    "SIZE_T", "ULONGLONG", "LONGLONG", "UINT_PTR", "HWINSTA",
    "HDESK", "PVOID", "HANDLE_PTR", "PTR64", "p64",
}


def width_of(rettype):
    t = rettype.strip()
    if t in ("VOID", "void"):
        return "void"
    if t in ("HRESULT", "SCODE"):
        return "hr"
    if t in ("float", "double", "f64"):
        return "f64"
    if t.endswith("*") or "PTR" in t or t in P64_TYPES:
        return "p64"
    return "i32"


def c_ident(dll, sym, used):
    base = dll.lower()
    if base.endswith(".dll"):
        base = base[:-4]
    s = "w32_stub_%s_%s" % (base, sym)
    s = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if s in used:
        i = 2
        while "%s_%d" % (s, i) in used:
            i += 1
        s = "%s_%d" % (s, i)
    used.add(s)
    return s


def read_rows(path, want_cols):
    rows = []
    for ln in open(path):
        if not ln.strip() or ln.startswith("#"):
            continue
        if ln.startswith("dll\t"):
            continue
        rows.append(ln.rstrip("\n").split("\t"))
    for r in rows:
        if len(r) != want_cols:
            raise SystemExit("gen_stubs: %s: want %d cols, got %d: %r" %
                             (path, want_cols, len(r), r))
    return rows


def gen_header(n_ord, n_stub, n_data):
    return """/* Generated by tools/w32_gen_stubs.py -- do not edit.
 * SPDX-License-Identifier: Apache-2.0 -- generated file, repository licence.
 *
 * W32A-1 loader tables: %(n_ord)d ordinals, %(n_stub)d stubs,
 * %(n_data)d data cells.  Sources: w32/ordinal_map.tsv (ordinal facts,
 * cited per row) and w32/stub_map.tsv (one row per ladder import the
 * static table in w32/src/w32_bind.c does not implement yet).
 *
 * A stub here is a bound address with an honest body: TODO stubs fail
 * loudly and name the phase that replaces them; FAILCLEAN stubs are the
 * final documented behaviour (mpr: no network provider).  Binding is not
 * behaviour (W32APP_PLAN.md W32A-1).
 */
#ifndef AURALITE_W32_GEN_H
#define AURALITE_W32_GEN_H

#include "w32/w32_bind.h"

/* Ordinal -> canonical name for one built-in module, or NULL when the
 * ordinal is unknown.  The caller resolves the NAME through the export
 * tables; an unknown ordinal refuses by number (D9). */
const char *w32_ordmap_lookup(const char *dll, unsigned ordinal);

/* The generated export table (TODO/FAILCLEAN/EXIT stubs + data cells),
 * NULL-terminated, same shape as w32_exports().  w32_resolve() falls
 * through to it after the static table. */
const w32_export_t *w32_gen_exports(void);

/* Bare module names the stub map covers ("kernel32", "mpr", ...),
 * NULL-terminated.  w32_module_init() registers each as a built-in so
 * GetModuleHandle/LoadLibrary find them; names already registered are
 * skipped, never duplicated. */
const char *const *w32_gen_modules(void);

#endif /* AURALITE_W32_GEN_H */
""" % {"n_ord": n_ord, "n_stub": n_stub, "n_data": n_data}


def main(argv):
    check_only = "--check" in argv

    ord_rows = read_rows(ORDMAP, 4)
    rows = read_rows(STUBMAP, 8)

    # Ordinal table first (deterministic: TSV order, already sorted).
    ords = []
    for dll, ordinal, name, _src in ord_rows:
        try:
            n = int(ordinal)
        except ValueError:
            raise SystemExit("gen_stubs: bad ordinal %r" % ordinal)
        if not 0 < n < 65536:
            raise SystemExit("gen_stubs: ordinal out of range: %d" % n)
        ords.append((dll.lower(), n, name))
    if len({(d, n) for d, n, _ in ords}) != len(ords):
        raise SystemExit("gen_stubs: duplicate ordinal row")

    used = set()
    stubs = []      # (dll, sym, kind, rettype, fail, phase, note, ident)
    for dll, sym, _cls, kind, rettype, fail, phase, note in rows:
        dll = dll.lower()
        if kind == "REAL":
            continue  # hand implementation; the checker pins it instead
        if kind not in ("TODO", "FAILCLEAN", "EXIT", "DATA"):
            raise SystemExit("gen_stubs: unknown kind %r (%s!%s)" %
                             (kind, dll, sym))
        if kind == "DATA":
            try:
                size = int(fail)
            except ValueError:
                raise SystemExit("gen_stubs: bad DATA size %r" % fail)
            if size <= 0 or size > 4096:
                raise SystemExit("gen_stubs: absurd DATA size %d" % size)
        elif kind == "EXIT":
            if rettype != "void" or fail != "-":
                raise SystemExit("gen_stubs: EXIT row must be void/-")
        else:
            width = width_of(rettype)
            if width == "void" and fail != "-":
                raise SystemExit("gen_stubs: void stub with fail %r" % fail)
            if width == "hr" and fail != "E_NOTIMPL":
                raise SystemExit("gen_stubs: HRESULT stub without E_NOTIMPL")
            if width == "p64" and fail not in ("0", "NULL", "-1", "-2"):
                raise SystemExit("gen_stubs: bad p64 fail %r" % fail)
            if width == "i32" and fail not in ("0", "E_NOTIMPL") and \
                    not (fail.isdigit() and int(fail) < 100000):
                raise SystemExit("gen_stubs: bad i32 fail %r" % fail)
            if width == "f64" and fail != "0":
                raise SystemExit("gen_stubs: bad f64 fail %r" % fail)
            if kind == "FAILCLEAN" and width != "i32":
                raise SystemExit("gen_stubs: FAILCLEAN must return i32")
        stubs.append((dll, sym, kind, rettype, fail, phase, note,
                      c_ident(dll, sym, used)))

    mods = sorted({d[:-4] if d.endswith(".dll") else d for d, _, _, _, _, _, _, _
                   in stubs} | {"kernel32", "user32", "gdi32"})

    n_data = sum(1 for s in stubs if s[2] == "DATA")
    n_fn = len(stubs) - n_data

    h_text = gen_header(len(ords), n_fn, n_data)

    L = []
    L.append("/* Generated by tools/w32_gen_stubs.py -- do not edit.  See the")
    L.append(" * header comment in w32/include/w32/w32_gen.h for what this is.")
    L.append(" * SPDX-License-Identifier: Apache-2.0 -- generated file, repository licence. */")
    L.append("")
    L.append('#include "w32/w32_gen.h"')
    L.append('#include "w32/w32_bind.h"')
    L.append('#include "w32/w32_errno.h"')
    L.append('#include "w32/w32_abi.h"')
    L.append('#include "w32/kernel32.h"')
    L.append("#include <stdint.h>")
    L.append("#include <stdio.h>")
    L.append("#include <string.h>")
    L.append("")
    L.append("/* E_NOTIMPL as a fact about the interface: 0x80004001.  Spelled")
    L.append(" * here, not copied from a header (w32/LICENSING.md). */")
    L.append("#define W32_E_NOTIMPL 0x80004001u")
    L.append("")
    L.append("/* ---- ordinal map ------------------------------------------------ */")
    L.append("")
    L.append("typedef struct { const char *dll; unsigned ord; const char *name; } ord_t;")
    L.append("")
    L.append("static const ord_t ordmap[] = {")
    for dll, n, name in ords:
        L.append('    { "%s", %d, "%s" },' % (dll, n, name))
    L.append("    { 0, 0, 0 }")
    L.append("};")
    L.append("")
    L.append("static int ord_ieq(const char *a, const char *b) {")
    L.append("    while (*a && *b) {")
    L.append("        char ca = *a, cb = *b;")
    L.append("        if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');")
    L.append("        if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');")
    L.append("        if (ca != cb) return 0;")
    L.append("        a++; b++;")
    L.append("    }")
    L.append("    return *a == 0 && *b == 0;")
    L.append("}")
    L.append("")
    L.append("const char *w32_ordmap_lookup(const char *dll, unsigned ordinal) {")
    L.append("    char base[64];")
    L.append("    size_t n = 0;")
    L.append("    if (!dll) return 0;")
    L.append("    while (dll[n] && n + 1 < sizeof base) { base[n] = dll[n]; n++; }")
    L.append("    base[n] = 0;")
    L.append("    if (n > 4 && ord_ieq(base + n - 4, \".dll\")) base[n - 4] = 0;")
    L.append("    for (const ord_t *o = ordmap; o->dll; o++) {")
    L.append("        char ob[64];")
    L.append("        size_t m = 0;")
    L.append("        while (o->dll[m] && m + 1 < sizeof ob) { ob[m] = o->dll[m]; m++; }")
    L.append("        ob[m] = 0;")
    L.append("        if (m > 4 && ord_ieq(ob + m - 4, \".dll\")) ob[m - 4] = 0;")
    L.append("        if (o->ord == ordinal && ord_ieq(ob, base)) return o->name;")
    L.append("    }")
    L.append("    return 0;")
    L.append("}")
    L.append("")
    L.append("/* ---- stubs ------------------------------------------------------ */")
    L.append("")
    L.append("static void note_todo(const char *dll, const char *sym,")
    L.append("                      const char *phase, int *once) {")
    L.append("    if (*once) return;")
    L.append("    *once = 1;")
    L.append('    printf("w32: TODO %s!%s needs %s (not yet implemented)\\n",')
    L.append("           dll, sym, phase);")
    L.append("}")
    L.append("")
    L.append("static void note_failclean(const char *dll, const char *sym,")
    L.append("                           const char *why, int *once) {")
    L.append("    if (*once) return;")
    L.append("    *once = 1;")
    L.append('    printf("w32: %s!%s: %s\\n", dll, sym, why);')
    L.append("}")
    L.append("")

    for dll, sym, kind, rettype, fail, phase, note, ident in stubs:
        tag = "%s!%s" % (dll, sym)
        if kind == "DATA":
            L.append("/* %s: DATA export, %s bytes, zeroed.  Bound by "
                     "address; never called. */" % (tag, fail))
            L.append("uint8_t %s[%s];" % (ident, fail))
            L.append("")
            continue
        if kind == "EXIT":
            L.append("/* %s: terminates.  A (void) stub would resume "
                     "after exit. */" % tag)
            L.append("W32ABI void %s(int code) {" % ident)
            L.append('    printf("w32: %s called, terminating\\n");' % tag)
            L.append("    ExitProcess((unsigned int)code);")
            L.append("}")
            L.append("")
            continue
        width = width_of(rettype)
        if width == "void":
            proto = "W32ABI void %s(void)" % ident
        elif width == "hr":
            proto = "W32ABI W32_DWORD %s(void)" % ident
        elif width == "f64":
            proto = "W32ABI double %s(void)" % ident
        elif width == "p64":
            proto = "W32ABI void *%s(void)" % ident
        else:
            proto = "W32ABI W32_DWORD %s(void)" % ident
        if kind == "FAILCLEAN":
            L.append("/* %s: FAIL-CLEAN (%s). */" % (tag, note))
            L.append("%s {" % proto)
            L.append("    static int once = 0;")
            L.append('    note_failclean("%s", "%s", "%s", &once);'
                     % (dll, sym, note))
            L.append("    return %s;" % (CODE_NAMES.get(fail, fail)))
            L.append("}")
        else:
            L.append("/* %s: TODO (%s).  Fails loudly until %s lands. */"
                     % (tag, note, phase))
            L.append("%s {" % proto)
            L.append("    static int once = 0;")
            L.append('    note_todo("%s", "%s", "%s", &once);'
                     % (dll, sym, phase))
            L.append("    w32_set_last_error(W32_ERROR_NOT_SUPPORTED);")
            if width == "void":
                L.append("    return;")
            elif width == "hr" or fail == "E_NOTIMPL":
                L.append("    return W32_E_NOTIMPL;")
            elif fail == "NULL":
                L.append("    return 0;")
            elif fail in ("-1", "-2"):
                L.append("    return (void *)(intptr_t)%s;" % fail)
            elif width == "f64":
                L.append("    return 0;")
            else:
                L.append("    return %s;" % fail)
            L.append("}")
        L.append("")

    L.append("/* ---- generated export table ------------------------------------- */")
    L.append("")
    L.append("static const w32_export_t gen_exports[] = {")
    for dll, sym, _kind, _rt, _fail, _ph, _note, ident in stubs:
        L.append('    { "%s", "%s", (void *)&%s },' % (dll, sym, ident))
    L.append("    { 0, 0, 0 }")
    L.append("};")
    L.append("")
    L.append("const w32_export_t *w32_gen_exports(void) { return gen_exports; }")
    L.append("")
    L.append("/* ---- stub-covered modules --------------------------------------- */")
    L.append("")
    L.append("static const char *const gen_modules[] = {")
    for m in mods:
        L.append('    "%s",' % m)
    L.append("    0")
    L.append("};")
    L.append("")
    L.append("const char *const *w32_gen_modules(void) { return gen_modules; }")
    L.append("")

    c_text = "\n".join(L)

    if check_only:
        ok = True
        if not os.path.isfile(OUT_C) or open(OUT_C).read() != c_text:
            print("gen_stubs: %s out of sync (re-run without --check)" % OUT_C)
            ok = False
        if not os.path.isfile(OUT_H) or open(OUT_H).read() != h_text:
            print("gen_stubs: %s out of sync (re-run without --check)" % OUT_H)
            ok = False
        if ok:
            print("gen_stubs: in sync (%d ordinals, %d stubs, %d data)" %
                  (len(ords), n_fn, n_data))
        return 0 if ok else 1

    open(OUT_C, "w").write(c_text)
    open(OUT_H, "w").write(h_text)
    print("gen_stubs: wrote %s + %s (%d ordinals, %d stubs, %d data)" %
          (OUT_C, OUT_H, len(ords), n_fn, n_data))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
