#!/usr/bin/env python3
"""Emit the W32A-1 harness's ground-truth header (build-time, hermetic).

The host harness (tests/unit/test_w32_a1.c) classifies every import of
every W32A-1 fixture the way the loader would bind it.  Two of its inputs
are DERIVED, never hand-copied, so they cannot drift from the sources:

  w32/src/w32_bind.c's static table  -> w32_a1_builtins[]  (dll, name)
  w32/stub_map.tsv                   -> w32_a1_stubclass[] (dll, name, class, kind)

The Makefile regenerates this header on every harness build; nothing is
committed.  A new REAL export or a re-classed stub row flows into the
harness with no edits anywhere.

Usage:
    python3 tools/w32_gen_a1_tables.py w32/src/w32_bind.c > $BUILD/w32_a1_tables.h
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_bind_statics(bind_c_path):
    """Read the static export table: { DLLMACRO|"dll", "name", addr }."""
    with open(bind_c_path, encoding="utf-8") as f:
        text = f.read()
    macros = dict(re.findall(r'#define\s+(\w+)\s+"([^"]+\.dll)"', text,
                             flags=re.IGNORECASE))
    rows = []
    for m in re.finditer(r'\{\s*(\w+|"[^"]+")\s*,\s*"([^"]+)"\s*,', text):
        dll, name = m.group(1), m.group(2)
        if dll.startswith('"'):
            dll = dll.strip('"')
        else:
            dll = macros.get(dll)
            if dll is None:
                continue  # not an export row (some other brace pair)
        rows.append((dll, name))
    # De-duplicate while keeping file order (the table wins ties by order).
    seen, uniq = set(), []
    for r in rows:
        if r not in seen:
            seen.add(r)
            uniq.append(r)
    return uniq


def parse_stubmap():
    """Read (dll, symbol, class, kind) from the committed stub map."""
    rows = []
    with open(os.path.join(ROOT, "w32", "stub_map.tsv"), encoding="utf-8") as f:
        for line in f:
            if not line.strip() or line.startswith("#"):
                continue
            cells = line.rstrip("\n").split("\t")
            if cells[0] == "dll":
                continue  # header row
            if len(cells) < 4:
                raise SystemExit("bad stub_map.tsv row: %r" % line)
            rows.append((cells[0], cells[1], cells[2], cells[3]))
    return rows


def c_str(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: w32_gen_a1_tables.py w32/src/w32_bind.c")
    builtins = parse_bind_statics(sys.argv[1])
    stubrows = parse_stubmap()
    if not builtins:
        raise SystemExit("no static exports parsed from %s" % sys.argv[1])
    if not stubrows:
        raise SystemExit("no rows parsed from w32/stub_map.tsv")
    print("/* Generated by tools/w32_gen_a1_tables.py -- do not edit. */")
    print("/* %d static builtins, %d stub-map rows. */"
          % (len(builtins), len(stubrows)))
    print("#ifndef AURALITE_W32_A1_TABLES_H")
    print("#define AURALITE_W32_A1_TABLES_H")
    print("")
    print("typedef struct { const char *dll; const char *name; }")
    print("    w32_a1_builtin_t;")
    print("static const w32_a1_builtin_t w32_a1_builtins[] = {")
    for dll, name in builtins:
        print("    { %s, %s }," % (c_str(dll), c_str(name)))
    print("    { 0, 0 }")
    print("};")
    print("")
    print("typedef struct { const char *dll; const char *name;")
    print("                 const char *cls; const char *kind; }")
    print("    w32_a1_stubclass_t;")
    print("static const w32_a1_stubclass_t w32_a1_stubclass[] = {")
    for dll, sym, cls, kind in stubrows:
        print("    { %s, %s, %s, %s }," % (c_str(dll), c_str(sym),
                                          c_str(cls), c_str(kind)))
    print("    { 0, 0, 0, 0 }")
    print("};")
    print("")
    print("#endif")


if __name__ == "__main__":
    main()
