/* user.c — Ring 3 execution + ELF loader test.
 *
 * Phase 8 proved Ring 3 entry + #GP recovery with a hand-assembled program.
 * Phase 9 replaces that with a compiled ELF binary (hello.elf) loaded by the
 * in-kernel ELF64 loader, proving the full chain: libc → SYSCALL → kernel.
 *
 * The user program runs as its own kernel thread so that TSS.RSP0 is isolated
 * from kmain, and any fault cleanly removes the thread.
 */

#include <stdint.h>
#include "kernel/proc/user.h"
#include "kernel/proc/scheduler.h"
#include "kernel/proc/thread.h"
#include "kernel/proc/elf.h"
#include "kernel/arch/x86_64/paging.h"
#include "kernel/arch/x86_64/cpu.h"
#include "kernel/arch/x86_64/gdt.h"
#include "kernel/arch/x86_64/tss.h"
#include "kernel/arch/x86_64/syscall.h"
#include "kernel/mm/kheap.h"
#include "kernel/mm/pmm.h"
#include "kernel/lib/kprintf.h"

#define USER_STACK_TOP         0x7FFFF0000000ULL    /* near top of user half */
#define USER_STACK_SIZE        0x10000ULL           /* usable bytes          */
#define USER_STACK_GUARD_SIZE  0x1000ULL            /* low guard page        */

/* Implemented in user_entry.asm — the actual iretq to Ring 3. */
extern void jump_to_user_asm(uint64_t entry, uint64_t stack_top,
                             uint64_t stack_bottom);

/* Generated by tools/gen_user_binary.py from the compiled init.elf (the shell). */
#include "init_bin.h"

void jump_to_user(uint64_t entry, uint64_t stack_top, uint64_t stack_bottom) {
    (void)stack_bottom;
    tcb_t *cur = sched_current();
    if (cur && cur->kernel_stack) {
        uint64_t kstack_top = (uint64_t)cur->kernel_stack + THREAD_STACK_SIZE;
        /* Set both the TSS RSP0 (for interrupt/exception transitions) and the
         * syscall handler's kernel stack (for SYSCALL transitions). */
        tss_set_rsp0(kstack_top);
        set_syscall_stack(kstack_top);
    }
    jump_to_user_asm(entry, stack_top, 0);
}

/*
 * Map the user stack pages (USER | PRESENT | WRITABLE). The code/data segments
 * are mapped by the ELF loader.
 */
static uint64_t choose_user_stack_top(void) {
    uint64_t pages = read_tsc() & 0xFULL; /* small per-launch entropy */
    return USER_STACK_TOP - pages * 0x1000ULL;
}

static int map_user_stack(uint64_t stack_top) {
    uint64_t stack_base = stack_top - USER_STACK_SIZE - USER_STACK_GUARD_SIZE;
    for (uint64_t off = USER_STACK_GUARD_SIZE; off < USER_STACK_GUARD_SIZE + USER_STACK_SIZE; off += 0x1000) {
        uint64_t phys = pmm_alloc_frame();
        if (phys == 0) {
            kprintf("[user] FAIL: OOM for user stack\n");
            return 0;
        }
        paging_map(stack_base + off, phys,
                   PAGE_FLAG_PRESENT | PAGE_FLAG_WRITABLE |
                   PAGE_FLAG_USER | PAGE_FLAG_NO_EXEC);
    }
    return 1;
}

/*
 * User test thread: load the compiled hello binary via the ELF loader, map the
 * stack, and jump to Ring 3. The program calls write(1, "hello\n", 6) and exits
 * cleanly via SYS_EXIT → thread_exit().
 */
static void user_test_thread(void *arg) {
    (void)arg;

    uint64_t shell_pml4 = paging_new_address_space();
    if (shell_pml4 == 0) {
        kprintf("[user] FAIL: could not create address space\n");
        return;
    }
    paging_switch_to(shell_pml4);

    tcb_t *cur = sched_current();
    if (cur) cur->pml4_phys = shell_pml4;

    uint64_t init_brk = 0;
    uint64_t entry = elf_load(init_bin, init_bin_size, &init_brk);
    if (cur) cur->brk = init_brk;
    if (entry == 0) { kprintf("[user] FAIL: ELF load failed\n"); return; }
    uint64_t stack_top = choose_user_stack_top();
    if (!map_user_stack(stack_top)) return;

    kprintf("[user] shell in isolated address space (CR3=0x%llx)\n",
            (unsigned long long)shell_pml4);
    jump_to_user(entry, stack_top - 16, 0);
}

void user_mode_self_test(void) {
    kprintf("[user] starting init shell in Ring 3...\n");

    tcb_t *t = kthread_create(user_test_thread, NULL, "init");
    if (t == NULL) {
        kprintf("[user] FAIL: could not create thread\n");
        return;
    }

    /* P10: the init shell is the root of the process tree — root its current
     * working directory at "/" so getcwd()/chdir() and every spawned child
     * (which inherits this cwd) start from a valid path. */
    t->cwd[0] = '/';
    t->cwd[1] = '\0';

    /* Give the shell a few scheduling slots to start up and print its banner. */
    for (int i = 0; i < 5; i++) {
        sched_yield();
    }

    /* This banner races with serial output from child user processes and can
     * splice itself into userspace log lines (e.g. selftest), confusing the
     * integration harness.  The shell prompt itself is the authoritative proof
     * that Ring 3 init is alive, so keep the yield-only behaviour here. */
    /* kmain does NOT halt here — it yields forever so the shell can run
     * interactively. The scheduler keeps kmain and the shell alternating;
     * when the shell blocks on read(stdin), kmain/idle take the slack. */
}
