/* tests/unit/test_printf_format.c — DOOM_PLAN.md D2.
 *
 * AuraLite's printf conversions, checked DIFFERENTIALLY against the host's
 * glibc: every case formats the same arguments with both and requires the
 * bytes to match. The oracle is the C standard as glibc implements it,
 * which is a far better reference than hand-written expectations — those
 * only ever encode what the author already believed.
 *
 * Every conversion here was missing or wrong, and each one was found the
 * same way: DOOM printed the format specifier instead of the value.
 *
 *   %i        absent entirely, so M_snprintf("joystick_physical_button%i")
 *             produced a literal "%i" and the config parser then rejected a
 *             variable by that name.
 *   %.Nd      the precision was PARSED and then dropped, so DOOM's font
 *             lump names came out as "STCFN%.3" and W_GetNumForName died
 *             on a lump that cannot exist.
 *   %f        absent, and DOOM writes floats into its config file. It would
 *             have read back the string "%f" as a number on the next run.
 *   %08.2f    width ignored for floats, found by this test rather than by
 *             the engine.
 *
 * The pattern is worth naming: a missing conversion does not fail loudly,
 * it silently emits the specifier as text, and the damage surfaces
 * somewhere far away as a nonsense lookup.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <string.h>

/* Generated by tools/extract_libc_impls.py from lib/libc/src/libc.c.
 * Renamed, because linking a test against a function the host also
 * provides silently tests the host's version instead. */
extern int auralite_snprintf(char *buf, size_t n, const char *fmt, ...);

static int passed = 0, failed = 0, tn = 0;

#define CHECK(cond, msg) do {                                              \
        if (cond) { passed++; }                                            \
        else { failed++; printf("    FAIL L%d: %s\n", __LINE__, (msg)); }  \
    } while (0)

#define RUN(f) do { tn++; printf("  [%d] %s\n", tn, #f); f(); } while (0)

/* Format the same arguments both ways and require identical bytes. */
#define SAME(...) do {                                                     \
        char a[128], g[128];                                               \
        int ra = auralite_snprintf(a, sizeof a, __VA_ARGS__);              \
        int rg = snprintf(g, sizeof g, __VA_ARGS__);                       \
        if (strcmp(a, g) != 0) {                                           \
            failed++;                                                      \
            printf("    FAIL L%d: %s -> ours [%s], glibc [%s]\n",          \
                   __LINE__, #__VA_ARGS__, a, g);                          \
        } else if (ra != rg) {                                             \
            failed++;                                                      \
            printf("    FAIL L%d: %s -> return %d, glibc %d\n",            \
                   __LINE__, #__VA_ARGS__, ra, rg);                        \
        } else { passed++; }                                               \
    } while (0)

/* ---- %d and %i --------------------------------------------------------- */

static void test_signed_decimal(void) {
    SAME("%d", 0);
    SAME("%d", 42);
    SAME("%d", -42);
    SAME("%d", 2147483647);
    SAME("%d", -2147483647 - 1);   /* INT_MIN: negation must not overflow */

    /* %i is the same conversion as %d for output (C11 7.21.6.1p8). They
     * differ only in *scanf, where %i honours a 0x/0 base prefix. */
    SAME("%i", 0);
    SAME("%i", -9);
    SAME("%i", 123456);
}

/* ---- field width and flags --------------------------------------------- */

static void test_width_and_flags(void) {
    SAME("[%5d]", 42);
    SAME("[%-5d]", 42);
    SAME("[%05d]", 42);
    SAME("[%5d]", -42);
    SAME("[%05d]", -42);          /* the sign precedes the zero padding */
    SAME("[%-5d]", -42);
    SAME("[%1d]", 123456);        /* width smaller than the value */

    /* TinyCC's diagnostics use argument-driven alignment and bounded source
     * excerpts, so test the * grammar rather than only literal fields. */
    SAME("[%*d]", 5, 42);
    SAME("[%*d]", -5, 42);        /* negative width implies '-' */
    SAME("[%.*d]", 3, 7);
    SAME("[%.*s]", 3, "abcdef");
    SAME("[%*.*s]", 6, 3, "abcdef");
    SAME("[%.*s]", -1, "abcdef");
}

/* ---- precision on integers --------------------------------------------- */

static void test_integer_precision(void) {
    /* A precision on an integer is a MINIMUM DIGIT COUNT, zero-filled --
     * not the same thing as a zero-padded width. */
    SAME("STCFN%.3d", 7);         /* the exact call that broke DOOM */
    SAME("%.3d", 42);
    SAME("%.5d", 123);
    SAME("%.1d", 99999);          /* precision below the digit count */
    SAME("%.3d", -42);            /* the sign is not part of the count */
    SAME("[%5.3d]", 42);          /* width and precision together */
    SAME("[%-6.3d]", 42);
    SAME("[%8.3d]", -42);

    /* "%.0d" of zero produces NO characters at all (C11 7.21.6.1p8). */
    SAME("[%.0d]", 0);
    SAME("[%.d]", 0);             /* an omitted precision means zero */
}

/* ---- %f ---------------------------------------------------------------- */

static void test_fixed_point(void) {
    SAME("%f", 0.0);
    SAME("%f", 3.14159);
    SAME("%f", -3.14159);         /* the default precision is 6 */
    SAME("%.2f", 2.345);
    SAME("%.0f", 9.6);            /* rounds, and emits no decimal point */
    SAME("%.3f", -0.5);
    SAME("%.2f", 0.999);          /* rounding carries into the integer part */
    SAME("%f", 1.0);
    SAME("%.1f", 0.05);
    SAME("[%08.2f]", 3.5);        /* zero padding after the sign */
    SAME("[%10.2f]", 3.5);
    SAME("[%-10.2f]", 3.5);
    SAME("[%08.2f]", -3.5);
}

/* ---- the non-finite floats --------------------------------------------- */

static void test_infinities_and_nan(void) {
    /* Built here rather than taken from <math.h> so the test does not
     * depend on the host's INFINITY/NAN macros expanding to a builtin. */
    volatile double zero = 0.0, one = 1.0, big = 1e308;
    double inf = big * 10.0;      /* overflows to +inf */
    double nan = zero / zero;     /* 0/0 is NaN */
    (void)one;

    SAME("%f", inf);
    SAME("%f", -inf);             /* the sign survives the inf branch */
    SAME("%.2f", inf);
    SAME("%f", nan);

    /* A mutation that dropped the sign inside the infinity branch survived
     * until these cases existed -- the finite path has its own copy of the
     * sign logic, so covering finite negatives proved nothing about it. */
}

/* ---- the other conversions, so this file covers the whole surface ------- */

static void test_other_conversions(void) {
    SAME("%s", "hello");
    SAME("[%10s]", "hi");
    SAME("[%-10s]", "hi");
    SAME("%c", 'x');
    SAME("%u", 4294967295u);
    SAME("%x", 0xdeadbeefu);
    SAME("%X", 0xdeadbeefu);
    SAME("%o", 0755u);
    SAME("%%");
    SAME("%ld", -1234567890123L);
    SAME("%lu", 1234567890123UL);
    SAME("%lx", 0x123456789abcUL);

    /* Mixed, in the shape real code writes. */
    SAME("%s=%d (%.1f%%)", "cpu", 42, 99.5);
}

/* ---- truncation -------------------------------------------------------- */

static void test_truncation(void) {
    /* snprintf must NUL-terminate within the buffer and return the length
     * it WOULD have written -- callers size buffers off that return. */
    char a[8], g[8];
    int ra = auralite_snprintf(a, sizeof a, "%d-%d-%d", 111, 222, 333);
    int rg = snprintf(g, sizeof g, "%d-%d-%d", 111, 222, 333);
    CHECK(strcmp(a, g) == 0, "truncated output must match glibc");
    CHECK(ra == rg, "truncated return value must match glibc");
    CHECK(a[sizeof a - 1] == '\0', "must NUL-terminate when truncating");

    /* A zero-sized buffer must not be written to at all. */
    char guard[4] = { 'A', 'A', 'A', 'A' };
    int r0 = auralite_snprintf(guard, 0, "%d", 12345);
    CHECK(guard[0] == 'A', "size 0 must not touch the buffer");
    CHECK(r0 == snprintf(NULL, 0, "%d", 12345), "size 0 returns the length");
}

int main(void) {
    printf("[unit] running test_printf_format (DOOM_PLAN D2)\n");
    RUN(test_signed_decimal);
    RUN(test_width_and_flags);
    RUN(test_integer_precision);
    RUN(test_fixed_point);
    RUN(test_infinities_and_nan);
    RUN(test_other_conversions);
    RUN(test_truncation);
    printf("[unit] test_printf_format: %d passed, %d failed\n", passed, failed);
    return failed == 0 ? 0 : 1;
}
