/* tests/unit/test_boot_offsets.c -- verify generated boot_info_t offsets.
 *
 * The BIOS Stage 2 assembler consumes build/boot_offsets.inc, and this host
 * unit test consumes build/boot_offsets.h.  Both files are generated by
 * tools/gen_boot_offsets.c from boot/shared/boot_info.h.  If boot_info_t moves
 * any field, these compile-time assertions fail unless the generated offsets
 * and the C struct layout remain in sync.
 */

#include <stddef.h>
#include <stdio.h>

#include "boot/shared/boot_info.h"
#include "boot_offsets.h"

#define STATIC_ASSERT_FIELD(field, constant) \
    _Static_assert(offsetof(boot_info_t, field) == (constant), \
                   "boot_info_t offset mismatch: " #field)

STATIC_ASSERT_FIELD(magic, BOOT_MAGIC_OFF_C);
STATIC_ASSERT_FIELD(fb, BOOT_FB_OFF_C);
STATIC_ASSERT_FIELD(mmap, BOOT_MMAP_OFF_C);
STATIC_ASSERT_FIELD(mmap_count, BOOT_MMAP_CNT_OFF_C);
STATIC_ASSERT_FIELD(hhdm_offset, BOOT_HHDM_OFF_C);
STATIC_ASSERT_FIELD(initrd_phys, BOOT_INITRD_P_OFF_C);
STATIC_ASSERT_FIELD(initrd_size, BOOT_INITRD_S_OFF_C);
STATIC_ASSERT_FIELD(cpu_count, BOOT_CPUCNT_OFF_C);
STATIC_ASSERT_FIELD(bsp_lapic_id, BOOT_BSP_LAPIC_OFF_C);
STATIC_ASSERT_FIELD(cpus, BOOT_CPUS_OFF_C);
STATIC_ASSERT_FIELD(rsdp_phys, BOOT_RSDP_OFF_C);
STATIC_ASSERT_FIELD(boot_from_uefi, BOOT_UEFI_OFF_C);
_Static_assert(sizeof(boot_info_t) == BOOT_INFO_SIZEOF_C,
               "boot_info_t sizeof mismatch");

int main(void) {
    puts("test_boot_offsets: ALL PASS");
    return 0;
}
